<?php
$title = 'Редактирование категории';
$this->headTitle($title);
?>

<section class="col col-lg-2">
    <p class="back"><span class="glyphicon glyphicon-arrow-left"></span> Назад</p>
</section>
<section class="col col-lg-7">
    <h3><?php echo $this->escapeHtml($title); ?></h3>
    <?php

    $form = $this->form;
    $form->setAttribute('action', $this->url('category',
        array('action' => 'edit',
              'id'     => $this->id,
        )));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));

    echo '<input type="hidden" name="parent_state" value="'. $this->parentState .'">';

    echo '<label><span>Список категорий:</span>' . "\n";
    echo '<select class="form-control category_select" name="idParent">' . "\n";
    echo $this->partialLoop('catalog/partial/categoryLoop.phtml', $this->categories);
    echo '</select>' . "\n";
    echo '</label><br>' . "\n";

    echo $this->formRow($form->get('name')) . '<br>';
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</section>