<?php
$title = 'Категории';
$this->headTitle($title);
?>

<section class="col col-lg-2">
    <p class="back"><span class="glyphicon glyphicon-arrow-left"></span> Назад</p>
</section>
<section class="col col-lg-7">
    <h3><?php echo $this->escapeHtml($title); ?></h3>

    <p>
        <a class="btn btn-success" href="<?php echo $this->url('category', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Добавить категорию</a>
    </p>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Название</th>
            <th>Действия</th>
        </tr>
        <?php for ($i = 0, $count = count($this->categories); $i < $count; $i++) : ?>
            <?php
                if ($this->categories[$i]['status'] != 4) {
                    $class = '';
                } else {
                    $class = 'hide_row';
                }
            ?>
            <tr class="<?php echo $class;?>">
                <td><?php echo $this->escapeHtml($this->categories[$i]['id']);?></td>
                <td><?php echo $this->escapeHtml($this->categories[$i]['name']);?></td>
                <td>
                    <a class="btn btn-primary" href="<?php echo $this->url('category',
                        array('action'=>'edit', 'id' => $this->categories[$i]['id']));?>"><span class="glyphicon glyphicon-edit"></span> Редактировать</a>
                    <a class="btn btn-warning show-hide" href="<?php echo $this->url('category',
                        array('action'=>'hide', 'id' => $this->categories[$i]['id']));?>"><span class="glyphicon glyphicon glyphicon-eye-close"></span> Скрыть</a>
<!--                    <a class="btn btn-danger" href="--><?php //echo $this->url('category',
//                        array('action'=>'delete', 'id' => $category->getId()));?><!--"><span class="glyphicon glyphicon-remove"></span> Удалить</a>-->
                </td>
            </tr>
        <?php endfor; ?>
    </table>
</section>