<a href="/register/add" class="btn btn-primary">Добавить запись</a>

<div>Установленные фильтры: &nbsp;
    <?php
        var_dump($this->filter);
    ?>
</div>

<div>

        <div>Выбрать: &nbsp;
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab0" data-toggle="tab"></a></li>
                <li><a href="#tab1" data-toggle="tab">Период</a></li>
                <li><a href="#tab2" data-toggle="tab">От кого</a></li>
                <li><a href="#tab3" data-toggle="tab">Кому</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab0"></div>
                <div class="tab-pane" id="tab1">
                    <form method="post" action="register/index">
                        Начало периода &nbsp;<input type="date" name="beginDate">
                        <input type="submit" class="btn btn-info" value="Готово">
                    </form>
                </div>
                <div class="tab-pane" id="tab2">
                    <p>Привет, я 2-я секция.</p>
                </div>
                <div class="tab-pane" id="tab3">
                    <p>Привет, я 3-я секция.</p>
                </div>
            </div>
        </div>

</div>
    <?php if ($this->paginator->count() > 0): ?>
        <table class="table">
            <tbody>
            <?php foreach($this->paginator as $item): ?>
                <tr>
                    <td><?php echo $item->getId(); ?></td>
                    <td><?php echo $item->getDate()->format('Y-m-d'); ?></td>
                    <td><?php echo $item->getIdStoreFrom()->getName(); ?></td>
                    <td><?php echo $item->getIdStoreTo()->getName(); ?></td>
                    <td><?php echo $item->getIdOperation()->getName(); ?></td>
                    <td><?php echo $item->getIdUser()->getEmail(); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <h3>Извините, записей с заданными условиями нет. <br>
            Измените критерии выбора.</h3>
    <?php endif ?>
<div class="clearfix"></div>
<section class="col col-lg-9 col-lg-offset-3 text-center">
    <?php
    echo (count($this->paginator) > 1) ? $this->paginationControl($this->paginator, 'Sliding', 'register/paginator/pagination.phtml') : "";
    ?>
</section>