<a href="<?php echo $this->url('register/add', array(
        'action'=>'add'));?>" class="btn btn-primary">Добавить запись</a>

<div class="delim"></div>
<div class="filter-criteria">Установленные фильтры: &nbsp;
    <form method="post" action="<?php echo $this->url('register', array('action' => 'index')); ?>">
    <?php
        foreach ($this->filter as $key => $value) {
            switch ($key) {
                case 'beginDate':
                    echo '<strong>начало периода:</strong> ';
                    break;
                case 'endDate':
                    echo '<strong> конец периода:</strong> ';
                    break;
                case 'storeFrom';
                    echo '<strong> от кого:</strong> ';
                    break;
                case 'storeTo';
                    echo '<strong> кому:</strong> ';
                    break;
                case 'operation';
                    echo '<strong> операция:</strong> ';
                    break;
                case 'paymentType';
                    echo '<strong> форма оплаты:</strong> ';
                    break;
                case 'status';
                    echo '<strong> статус:</strong> ';
                    break;
                case 'user';
                    echo '<strong> пользователь:</strong> ';
                    break;
            }
            echo $value; ?>
            <label class="btn-remove">
                <input type="submit" class="btn btn-danger hide" name="<?php echo $key . 'Reset'; ?>">
                <span class="glyphicon glyphicon-remove cross" data-toggle="tooltip" data-placement="top" title="Удалить фильтр"></span>
            </label>
    <?php } ?>
    </form>
</div>

<div>
    <div>
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab0" data-toggle="tab">Выбрать:</a></li>
            <li><a href="#tab1" data-toggle="tab">период</a></li>
            <li><a href="#tab2" data-toggle="tab">от кого</a></li>
            <li><a href="#tab3" data-toggle="tab">кому</a></li>
            <li><a href="#tab4" data-toggle="tab">тип операции</a></li>
            <li><a href="#tab5" data-toggle="tab">форму оплаты</a></li>
            <li><a href="#tab6" data-toggle="tab">статус</a></li>
            <li><a href="#tab7" data-toggle="tab">пользователя</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab0"></div>
            <div class="tab-pane" id="tab1">
                <form method="post" action="<?php echo $this->url('register',
                    array('action' => 'index')); ?>">
                    начало периода &nbsp;<input type="date" name="beginDate">
                    &nbsp; конец периода &nbsp;<input type="date" name="endDate">
                    <input type="submit" class="btn btn-info" value="Готово">
                </form>
            </div>
            <div class="tab-pane" id="tab2">
                <?php foreach ($this->data['storeFrom'] as $store) { ?>
                    <form class="float-form" method="post" action="<?php echo $this->url('register', array('action' => 'index')); ?>">
                        <input type="submit" class="btn btn-link" name="storeFrom" value="<?php echo $store->getName(); ?>">
                        <input type="hidden" name="idStoreFrom" value="<?php echo $store->getId(); ?>">
                    </form>
                <?php } ?>
            </div>
            <div class="tab-pane" id="tab3">
                <?php foreach ($this->data['storeTo'] as $store) { ?>
                    <form class="float-form" method="post" action="<?php echo $this->url('register', array('action' => 'index')); ?>">
                        <input type="submit" class="btn btn-link" name="storeTo" value="<?php echo $store->getName(); ?>">
                        <input type="hidden" name="idStoreTo" value="<?php echo $store->getId(); ?>">
                    </form>
                <?php } ?>
            </div>
            <div class="tab-pane" id="tab4">
                <?php foreach ($this->data['operation'] as $operation) { ?>
                    <form class="float-form" method="post" action="<?php echo $this->url('register', array('action' => 'index')); ?>">
                        <input type="submit" class="btn btn-link" name="operation" value="<?php echo $operation->getName(); ?>">
                        <input type="hidden" name="idOperation" value="<?php echo $operation->getId(); ?>">
                    </form>
                <?php } ?>
            </div>
            <div class="tab-pane" id="tab5">
                <?php foreach ($this->data['paymentType'] as $paymentType) { ?>
                    <form class="float-form" method="post" action="<?php echo $this->url('register', array('action' => 'index')); ?>">
                        <input type="submit" class="btn btn-link" name="paymentType" value="<?php echo $paymentType->getName(); ?>">
                        <input type="hidden" name="idPaymentType" value="<?php echo $paymentType->getId(); ?>">
                    </form>
                <?php } ?>
            </div>
            <div class="tab-pane" id="tab6">
                <?php foreach ($this->data['status'] as $status) { ?>
                    <form class="float-form" method="post" action="<?php echo $this->url('register', array('action' => 'index')); ?>">
                        <input type="submit" class="btn btn-link" name="status" value="<?php echo $status->getName(); ?>">
                        <input type="hidden" name="idStatus" value="<?php echo $status->getId(); ?>">
                    </form>
                <?php } ?>
            </div>
            <div class="tab-pane" id="tab7">
                <?php foreach ($this->data['user'] as $user) { ?>
                    <form class="float-form" method="post" action="<?php echo $this->url('register', array('action' => 'index')); ?>">
                        <input type="submit" class="btn btn-link" name="user" value="<?php echo $user->getEmail(); ?>">
                        <input type="hidden" name="idUser" value="<?php echo $user->getId(); ?>">
                    </form>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
    <?php if ($this->paginator->count() > 0): ?>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Дата</th>
                <th>От кого</th>
                <th>Кому</th>
                <th>Тип операции</th>
                <th>Пользователь</th>
                <th>Сумма</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->paginator as $item): ?>
                <tr>
                    <td><?php echo $item->getId(); ?></td>
                    <td><?php echo $item->getDate()->format('d.m.Y'); ?></td>
                    <td><?php echo $item->getIdStoreFrom()->getName(); ?></td>
                    <td><?php echo $item->getIdStoreTo()->getName(); ?></td>
                    <td><?php echo $item->getIdOperation()->getName(); ?></td>
                    <td><?php echo $item->getIdUser()->getEmail(); ?></td>
                    <td><?php echo $item->getTotalSum(); ?></td>
                    <td>
                        <form class="float-form" method="post" action="<?php echo $this->url('register-table', array('action' => 'get-detail')); ?>">
                            <input type="submit" class="btn btn-info" name="detailRegister" value="Детали">
                            <input type="hidden" name="idRegister" value="<?php echo $item->getId(); ?>">
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <h3>Извините, записей с заданными условиями нет. <br>
            Измените критерии выбора.</h3>
    <?php endif ?>
<div class="delim"></div>
<section class="col col-md-12 text-center">
    <?php
    echo (count($this->paginator) > 1) ? $this->paginationControl($this->paginator, 'Sliding', 'register/paginator/pagination.phtml') : "";
    ?>
</section>