<?php
$title = 'Способ доставки';
$this->headTitle($title);
?>
<section class="col col-lg-2">
    <p class="back"><span class="glyphicon glyphicon-arrow-left"></span> Назад</p>
</section>
<section class="col col-lg-7">
    <h3><?php echo $this->escapeHtml($title); ?></h3>
    <p>
        <a class="btn btn-success" href="<?php echo $this->url('data/delivery-method', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Добавить способ доставки</a>
    </p>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Название</th>
            <th>Действия</th>
        </tr>
        <?php for ($i = 0, $count = count($this->delivery); $i < $count; $i++) : ?>
            <?php
            if (is_object($this->delivery[$i]->getIdStatus())) {
                if ($this->delivery[$i]->getIdStatus()->getId() != 4) {

                    $class = '';
                } else {
                    $class = 'hide_row';
                }
            } else {
                $class = '';
            }
            ?>
            <tr class="<?php echo $class;?>">
                <td><?php echo $this->escapeHtml($this->delivery[$i]->getId());?></td>
                <td><?php echo $this->escapeHtml($this->delivery[$i]->getName());?></td>
                <td>
                    <a class="btn btn-primary" href="<?php echo $this->url('data/delivery-method',
                        array('action'=>'edit', 'id' => $this->delivery[$i]->getId()));?>"><span class="glyphicon glyphicon-edit"></span> Редактировать</a>
                    <a class="btn btn-warning show-hide" href="<?php echo $this->url('data/delivery-method',
                        array('action'=>'hide', 'id' => $this->delivery[$i]->getId()));?>"><span class="glyphicon glyphicon glyphicon-eye-close"></span> Скрыть</a>
                </td>
            </tr>
        <?php endfor; ?>
    </table>
</section>