<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Gallery\Module'                     => __DIR__ . '/Module.php',
  'Gallery\Controller\IndexController' => __DIR__ . '/src/Gallery/Controller/IndexController.php',
);
