<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Gallery\Module'                     => __DIR__ . '/Module.php',
  'Gallery\Controller\EditController'  => __DIR__ . '/src/Gallery/Controller/EditController.php',
  'Gallery\Controller\IndexController' => __DIR__ . '/src/Gallery/Controller/IndexController.php',
  'Gallery\Entity\Gallery'             => __DIR__ . '/src/Gallery/Entity/Gallery.php',
  'Gallery\Form\ImgUploadForm'         => __DIR__ . '/src/Gallery/Form/ImgUploadForm.php',
);
