<?php
$title = 'Добавить способ оплаты';
$this->headTitle($title);
?>

<section class="col col-md-2">
    <p class="back"><span class="glyphicon glyphicon-arrow-left"></span> Назад</p>
</section>
<section class="col col-md-7">
    <h3><?php echo $this->escapeHtml($title); ?></h3>
    <?php

    $form = $this->form;
    $form->setAttribute('action', $this->url('data/payment-method', array('action' => 'add')));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo '<div class="form-group">'.
        $this->formRow($form->get('name')) .
        $this->formSubmit($form->get('submit')) .
        '</div>';
    echo $this->form()->closeTag();
    ?>
</section>