<?php
$title = 'Редактирование способ jgkfns';
$this->headTitle($title);
?>

<section class="col col-lg-2">
    <p class="back"><span class="glyphicon glyphicon-arrow-left"></span> Назад</p>
</section>
<section class="col col-lg-7">
    <h3><?php echo $this->escapeHtml($title); ?></h3>
    <?php

    $form = $this->form;
    $form->setAttribute('action', $this->url('data/payment-method',
            array('action' => 'edit',
                  'id'     => $this->id,
            )));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('name')) . '<br>';
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</section>