<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Register\Module'                                   => __DIR__ . '/Module.php',
  'Register\Controller\BalanceController'             => __DIR__ . '/src/Register/Controller/BalanceController.php',
  'Register\Controller\IndexController'               => __DIR__ . '/src/Register/Controller/IndexController.php',
  'Register\Controller\OrderController'               => __DIR__ . '/src/Register/Controller/OrderController.php',
  'Register\Controller\PaymentController'             => __DIR__ . '/src/Register/Controller/PaymentController.php',
  'Register\Controller\RegisterController'            => __DIR__ . '/src/Register/Controller/RegisterController.php',
  'Register\Controller\RegisterTableController'       => __DIR__ . '/src/Register/Controller/RegisterTableController.php',
  'Register\Controller\RemainsController'             => __DIR__ . '/src/Register/Controller/RemainsController.php',
  'Register\Controller\UserController'                => __DIR__ . '/src/Register/Controller/UserController.php',
  'Register\Entity\Payment'                           => __DIR__ . '/src/Register/Entity/Payment.php',
  'Register\Entity\Register'                          => __DIR__ . '/src/Register/Entity/Register.php',
  'Register\Entity\RegisterTable'                     => __DIR__ . '/src/Register/Entity/RegisterTable.php',
  'Register\Model\Register'                           => __DIR__ . '/src/Register/Model/Register.php',
  'Register\View\Helper\Factory\RequestHelperFactory' => __DIR__ . '/src/Register/View/Helper/Factory/RequestHelperFactory.php',
  'Register\View\Helper\Requesthelper'                => __DIR__ . '/src/Register/View/Helper/Requesthelper.php',
);
