<?php
$title = ' ';
if (!is_null($this->breadcrumbs)) {
    foreach ($this->breadcrumbs as $key => $value) {
        $title .= $value['name'] . ' ';
    }
} else {
    $title .= 'Все продукты';
}
$this->headTitle($title);
?>
<section class="col col-md-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> <span class="product-list">Каталог товаров</span></h3>
        <div class="delim"></div>
        <!-- Accordion -->
        <?php echo $this->catalog ;?><!-- /Accordion -->
    </aside>
</section>

<section class="col col-md-9">
    <?php if (!is_null($this->breadcrumbs)) : ?>
        <div class="filter-criteria">
            <?php foreach ($this->breadcrumbs as $key => $value) : ?>
                <span>
                    <strong><?php echo $value['name']; ?></strong>
                    <a href="/product" data-link="<?php echo $value['translit'];?>">
                        <i class="glyphicon glyphicon-remove cross-link" data-toggle="tooltip" data-placement="top" title="Удалить фильтр"></i>&nbsp;
                    </a>
                </span>
            <?php endforeach; ?>
        </div>
    <?php endif ?>
    <div class="delim"></div>
</section>

<section class="col col-md-9 product-holder">
    <?php if ($this->paginator->count() > 0): ?>
        <?php foreach ($this->paginator as $item): ?>
            <?php if (is_null($item[0]->getIdStatus()) || ($item[0]->getIdStatus()->getId() == 3)): ?>
                <section class="product row">
                    <div class="col col-md-4">
                        <?php if ($item[0]->getImg()): ?>
                            <a href="<?php echo $this->url('product/view', array('action' => 'view', 'name' => $item[0]->getTranslit()));?>">
                                <img class="lazy img-responsive set-product-in-store store-img" data-original="/img/product/min/<?php echo $item[0]->getImg();?>" width="270" alt="">
                            </a>
                        <?php else : ?>
                            <a href="<?php echo $this->url('product/view', array('action' => 'view', 'name' => $item[0]->getTranslit()));?>">
                                <img class="lazy" data-original="/img/product/min/noimage.png" width="270" alt="">
                            </a>
                        <?php endif; ?>
                    </div>
                    <div class="col col-md-8">
                        <h5>
                            <a class="set-product-in-store store-href" href="<?php echo $this->url('product/view', array('action' => 'view', 'name' => $item[0]->getTranslit()));?>"><?php echo $item[0]->getName(); ?></a>
                        </h5>
                        <p class="store-description"><?php echo $item[0]->getDescription(); ?></p>
                        <?php if ($item['quantity'] === 0 &&  $item['virtualQty'] > 0) : ?>
                            <p class="product-delivery">Доставка в течении 2-3 дней</p>
                        <?php endif; ?>
                        <?php if ($item[0]->getPrice() !== 0) : ?>
                            <p class="product-price store-price"><?php echo $item[0]->getPrice() / 100; ?></p>
                        <?php endif; ?>
                    </div>
                    <div class="cart-form">
                        <?php if ($item['quantity'] > 0 || $item['virtualQty'] > 0) : ?>
                            <!-- Add to cart -->
                            <form action="<?php echo $this->url('cart/default', array('action' => 'add'));?>" method="post" class="form-inline add-to-cart">
                                <input type="hidden" class="id" name="id" value="<?php echo $item[0]->getId(); ?>">
                                <input type="hidden" class="continue" name="continue">
                                <?php if (!in_array($item[0]->getId(), $this->inCart)) : /* Если товар еще не в корзине */ ?>
                                    <input type="submit" value="В корзину" name="addToCart" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Добавить">
                                <?php else : ?>
                                    <input type="button" value="Уже в корзине" class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Товар уже в корзине">
                                <?php endif; ?>
                            </form><!-- /Add to cart -->
                        <?php endif; ?>
                        <?php if (!in_array($item[0]->getId(), $this->inCart)) : /* Если товар еще не в корзине */ ?>
                            <!-- One click buy -->
                            <form class="form-inline">
                                <input type="hidden" class="id" name="id" value="<?php echo $item[0]->getId(); ?>">
                                <?php if ($item['quantity'] === 0 &&  $item['virtualQty'] > 0) : ?>
                                    <input type="hidden" class="qty" name="qty" value="<?php echo $item['virtualQty']; ?>">
                                <?php else : ?>
                                    <input type="hidden" class="qty" name="qty" value="<?php echo $item['quantity']; ?>">
                                <?php endif; ?>
                                <?php if ($item['quantity'] < 1 && $item['virtualQty'] < 1) : ?>
                                    <input type="button" value="Заказать" name="order" class="btn btn-warning order-product md-trigger" data-modal="modal-3" data-toggle="tooltip" data-placement="top" title="Заказ товара">
                                <?php else : ?>
                                    <input type="button" value="Купить" name="oneClickBuy" class="btn btn-success one-click-buy md-trigger" data-modal="modal-1" data-toggle="tooltip" data-placement="top" title="в 1 клик">
                                <?php endif; ?>
                            </form><!-- /One click buy -->
                        <?php endif; ?>
                    </div>
                </section>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php else : ?>
        <h3>Извините, такого товара нет в магазине. <br>
            Вы можете воспользоваться поиском или изменить критерии выбора.</h3>
    <?php endif; ?>
</section>

<div class="md-modal md-effect-1" id="modal-1">
    <div class="md-content">
        <h3 class="one-click-buy-info">Купить товар</h3>
        <div>
            <p class="one-click-buy-info">Для подтверждения заказа, укажите свой <strong>номер телефона</strong> и желаемое <strong>количество</strong> в поле ввода:</p>
            <div class="one-click-buy-form">
                <form action="<?php echo $this->url('cart');?>" method="post" class="form-inline" role="form">
                    <input name="id[]" type="hidden" class="one-click-buy-product-input-id">
                    <div class="products-buy">
                        <div class="one-click-buy-product-name"></div>
                        <input name="qty[]" class="form-control one-click-buy-number" type="number" min="1" step="1" value="1" data-toggle="tooltip" data-placement="top" title="Укажите желаемое к-во">
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon form-addon">+380</div>
                            <input name="phone" class="form-control one-click-buy-input" type="tel" value="<?php echo $this->userInfo['phone'] ;?>" placeholder="Ваш номер" data-toggle="tooltip" data-placement="top" title="Укажите Ваш номер телефона" required>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-success one-click-buy-submit" name="oneClickBuy" value="Готово">
                </form>
            </div>
            <?php if (!$this->zfcUserIdentity()): ?>
            <p class="bg-info">Так же, вы можете войти в систему используя свои данные: <a href="<?php echo $this->url('zfcuser/login') . '#log'; ?>">Вход</a></p>
            <?php endif ?>
            <button type="button" class="close md-close"><span aria-hidden="true">&times;</span><span class="sr-only">Закрыть</span></button>
        </div>
    </div>
</div>

<div class="md-modal md-effect-1" id="modal-3">
    <div class="md-content">
        <h3 class="order-info-header">Заказать товар</h3>
        <div>
            <p class="order-info">Для подтверждения заказа, укажите свой <strong>номер телефона</strong> в поле ввода:</p>
            <div class="order-form">
                <form action="<?php echo $this->url('cart');?>" method="post" class="form-inline" role="form">
                    <input name="id[]" type="hidden" class="order-product-input-id">
                    <div class="products-buy">
                        <div class="order-product-name"></div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon form-addon">+380</div>
                            <input name="phone" class="form-control order-input" type="tel" value="<?php echo $this->userInfo['phone'] ;?>" placeholder="Ваш номер" data-toggle="tooltip" data-placement="top" title="Укажите Ваш номер телефона" required>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-success order-submit" name="order" value="Готово">
                </form>
            </div>
            <?php if (!$this->zfcUserIdentity()): ?>
                <p class="bg-info">Так же, вы можете войти в систему используя свои данные: <a href="<?php echo $this->url('zfcuser/login') . '#log'; ?>">Вход</a></p>
            <?php endif ?>
            <button type="button" class="close md-close"><span aria-hidden="true">&times;</span><span class="sr-only">Закрыть</span></button>
        </div>
    </div>
</div>
<div class="md-overlay"></div>

<section class="col col-md-9 col-md-offset-3 text-center paginator-holder">
    <div class="delim"></div>
<?php
    echo (count($this->paginator) > 1) ? $this->paginationControl($this->paginator, 'Sliding', 'product/paginator/pagination.phtml', array('params' => $this->seoUrlParams)) : "";
?>
</section>