<section class="col col-lg-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> <span class="product-list">Каталог товаров</span></h3>
        <!-- Accordion -->
        <?php echo $this->catalog ;?><!-- /Accordion -->
    </aside>
</section>

<section class="col col-lg-9">
    <?php if (!is_null($this->product->getImg())) : ?>
    <div class="product-image">
        <img class="img-responsive" src="/img/product/<?php echo $this->product->getImg(); ?>" alt="">
    </div>
    <?php endif ?>
    <h2 class="product-name">
        <?php echo $this->product->getName(); ?>
    </h2>
    <p class="product-description">
        <?php echo $this->product->getDescription(); ?>
    </p>
    <h3 class="product-price">
        <?php echo $this->product->getPrice() / 100; ?>
    </h3>
</section>