<section class="col col-md-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> <span class="product-list">Каталог товаров</span></h3>
        <div class="delim"></div>
        <!-- Accordion -->
        <?php echo $this->catalog ;?><!-- /Accordion -->
    </aside>
</section>

<section class="col col-md-9">
    <h3 class="product-name">
        <?php echo $this->product[0]->getName(); ?>
    </h3>
    <div class="product-image">
        <?php if (!is_null($this->product[0]->getImg())) : ?>
            <?php
            // Определить ширину изображения
            $size = getimagesize('./public/img/product/' . $this->product[0]->getImg());
            $flag = (int) $size[0] > 400 ? true : false;
            ?>
            <?php if ($flag) : /* если ширина более 400 - увеличение изображения при клике */?>
            <a href="/img/product/<?php echo $this->product[0]->getImg(); ?>" data-lightbox="image">
                <img class="img-responsive" src="/img/product/<?php echo $this->product[0]->getImg(); ?>" alt="">
                <i class="glyphicon glyphicon-zoom-in zoom"></i>
            </a>
            <?php else : /* просто вернуть изображение */?>
                <img class="img-responsive" src="/img/product/<?php echo $this->product[0]->getImg(); ?>" alt="">
            <?php endif ?>
        <?php else : ?>
            <img src="/img/product/noimage.png" width="270" alt="">
        <?php endif ?>
    </div>
    <h4 class="product-description">
        <?php echo $this->product[0]->getDescription(); ?>
    </h4>
    <?php if ($this->product['quantity'] === 0 &&  $this->product['virtualQty'] > 0) : ?>
        <p class="product-delivery">Доставка в течении 2-3 дней</p>
    <?php endif; ?>
    <h3 class="product-price">
        <?php echo $this->product[0]->getPrice() / 100; ?>
    </h3>
    <div class="cart-form-single-product">
        <?php if ($this->product['quantity'] > 0 || $this->product['virtualQty'] > 0) : ?>
            <!-- Add to cart -->
            <form action="<?php echo $this->url('cart/default', array('action' => 'add'));?>" method="post" class="form-inline add-to-cart">
                <input type="hidden" class="id" name="id" value="<?php echo $this->product[0]->getId(); ?>">
                <input type="hidden" class="continue" name="continue">
                <?php if (!in_array($this->product[0]->getId(), $this->inCart)) : ?>
                    <input type="submit" value="В корзину" name="addToCart" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Добавить">
                <?php else : ?>
                    <input type="button" value="Уже в корзине" class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Товар уже в корзине">
                <?php endif; ?>
            </form><!-- /Add to cart -->
        <?php endif; ?>
        <?php if (!in_array($this->product[0]->getId(), $this->inCart)) : /* Если товар еще не в корзине */ ?>
            <form class="form-inline">
                <!-- One click buy -->
                <input type="hidden" class="id" name="id" value="<?php echo $this->product[0]->getId(); ?>">
                <?php if ($this->product['quantity'] === 0 &&  $this->product['virtualQty'] > 0) : ?>
                    <input type="hidden" class="qty" name="qty" value="<?php echo $this->product['virtualQty']; ?>">
                <?php else : ?>
                    <input type="hidden" class="qty" name="qty" value="<?php echo $this->product['quantity']; ?>">
                <?php endif; ?>
                <?php if ($this->product['quantity'] < 1 && $this->product['virtualQty'] < 1) : ?>
                    <input type="button" value="Заказать" name="order" class="btn btn-warning order-product md-trigger" data-modal="modal-3" data-toggle="tooltip" data-placement="top" title="Заказ товара">
                <?php else : ?>
                    <input type="button" value="Купить" name="oneClickBuy" class="btn btn-success one-click-buy md-trigger" data-modal="modal-1" data-toggle="tooltip" data-placement="top" title="в 1 клик">
                <?php endif; ?>
            </form><!-- /One click buy -->
        <?php endif; ?>
    </div>
</section>

<div class="md-modal md-effect-1" id="modal-1">
    <div class="md-content">
        <h3>
            Купить товар <br>
            <span class="one-click-buy-product-name"></span>
        </h3>
        <div>
            <p>Для подтверждения заказа, укажите свой <strong>номер телефона</strong> и желаемое <strong>количество</strong> в поле ввода:</p>
            <div class="one-click-buy-form">
                <form action="<?php echo $this->url('cart');?>" method="post" class="form-inline" role="form">
                    <input name="id[]" type="hidden" class="one-click-buy-product-input-id">
                    <div class="products-buy">
                        <div><?php echo $this->product[0]->getName(); ?></div>
                        <input name="qty[]" class="form-control one-click-buy-number" type="number" min="1" step="1" value="1" data-toggle="tooltip" data-placement="top" title="Укажите желаемое к-во">
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon form-addon">+380</div>
                            <input name="phone" class="form-control one-click-buy-input" type="tel" value="<?php echo $this->userInfo['phone'] ;?>" placeholder="Ваш номер" data-toggle="tooltip" data-placement="top" title="Укажите Ваш номер телефона" required>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-success one-click-buy-submit" name="oneClickBuy" value="Готово">
                </form>
            </div>
            <?php if (!$this->zfcUserIdentity()): ?>
                <p class="bg-info">Так же, вы можете войти в систему используя свои данные: <a href="<?php echo $this->url('zfcuser/login') . '#log'; ?>">Вход</a></p>
            <?php endif ?>
            <button type="button" class="close md-close"><span aria-hidden="true">&times;</span><span class="sr-only">Закрыть</span></button>
        </div>
    </div>
</div>

<div class="md-modal md-effect-1" id="modal-3">
    <div class="md-content">
        <h3 class="order-info-header">Заказать товар</h3>
        <div>
            <p class="order-info">Для подтверждения заказа, укажите свой <strong>номер телефона</strong> в поле ввода:</p>
            <div class="order-form">
                <form action="<?php echo $this->url('cart');?>" method="post" class="form-inline" role="form">
                    <input name="id[]" type="hidden" class="order-product-input-id">
                    <div class="products-buy">
                        <div class="order-product-name"></div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon form-addon">+380</div>
                            <input name="phone" class="form-control order-input" type="tel" value="<?php echo $this->userInfo['phone'] ;?>" placeholder="Ваш номер" data-toggle="tooltip" data-placement="top" title="Укажите Ваш номер телефона" required>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-success order-submit" name="order" value="Готово">
                </form>
            </div>
            <?php if (!$this->zfcUserIdentity()): ?>
                <p class="bg-info">Так же, вы можете войти в систему используя свои данные: <a href="<?php echo $this->url('zfcuser/login') . '#log'; ?>">Вход</a></p>
            <?php endif ?>
            <button type="button" class="close md-close"><span aria-hidden="true">&times;</span><span class="sr-only">Закрыть</span></button>
        </div>
    </div>
</div>
<div class="md-overlay"></div>
<script>$('head').append('<link rel="stylesheet" href="/lightbox/lightbox.min.css">');</script>
<script src="/lightbox/lightbox.min.js"></script>