<section id="accordion">

    <?php echo $this->showList($this->categoryList, $this->seoUrlParams); ?>

    <hr class="delim">

    <div class="accordion">
        <h3 class="filled">Производители</h3>
        <div>
            <?php
            $seoUrlParams = $this->seoUrlParams;
            $flag         = $this->sessionFlag;

            if (isset($flag['catalog']) && !isset($flag['brand'])) {
                $seoUrlParams['param2'] = $seoUrlParams['param1'];
            }

            foreach ($this->brandList as $brand) {
                $seoUrlParams['param1'] = $brand['translit'];

                echo '<a href="' .
                    $this->url('product/seoUrl', $seoUrlParams)
                    . '" class="empty catalog-link">' . $brand['name'] . '</a>' . "\n";
            }
            ?>
        </div>
    </div>
</section>