<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Catalog\Module'                       => __DIR__ . '/Module.php',
  'Catalog\Controller\BrandController'   => __DIR__ . '/src/Catalog/Controller/BrandController.php',
  'Catalog\Controller\CatalogController' => __DIR__ . '/src/Catalog/Controller/CatalogController.php',
  'Catalog\Controller\IndexController'   => __DIR__ . '/src/Catalog/Controller/IndexController.php',
  'Catalog\Entity\Brand'                 => __DIR__ . '/src/Catalog/Entity/Brand.php',
  'Catalog\Entity\Catalog'               => __DIR__ . '/src/Catalog/Entity/Catalog.php',
  'Catalog\Model\Brand'                  => __DIR__ . '/src/Catalog/Model/Brand.php',
  'Catalog\Model\Catalog'                => __DIR__ . '/src/Catalog/Model/Catalog.php',
  'Catalog\View\Helper\ShowList'         => __DIR__ . '/src/Catalog/View/Helper/ShowList.php',
);
