<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Article\Module'                      => __DIR__ . '/Module.php',
  'Article\Controller\EditController'   => __DIR__ . '/src/Article/Controller/EditController.php',
  'Article\Controller\IndexController'  => __DIR__ . '/src/Article/Controller/IndexController.php',
  'Article\Controller\UploadController' => __DIR__ . '/src/Article/Controller/UploadController.php',
  'Article\Entity\Article'              => __DIR__ . '/src/Article/Entity/Article.php',
  'Article\Form\ImgUploadForm'          => __DIR__ . '/src/Article/Form/ImgUploadForm.php',
);
