<div class="col col-lg-7 col-lg-offset-2 form_wrap">
<?php

$form = $this->form;
$form->setAttribute('action', $this->url('fileupload',
    array('controller'=>'upload', 'action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);

echo '<div class="form-group">' .
    $this->formRow($form->get('file')) .
    '</div>';

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>