<?php
    $data = $this->product->getVariables();
?>
<link rel="stylesheet" href="/css/jquery.dataTables.css">
<link rel="stylesheet" href="/css/shCore.css">

<section class="col col-lg-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> Каталог товаров</h3>
        <span class="link-type" data-type="<?php echo $this->type;?>"></span>
        <!-- Accordion -->
        <?php echo $this->catalog ;?><!-- /Accordion -->
    </aside>
</section>

<section class="col col-lg-9">
    <?php if (count($data['breadcrumbs']) > 0) : ?>
        <ol class="breadcrumb">
            <?php
            foreach ($data['breadcrumbs'] as $key => $value) {
                if (is_object($value)) {
                    echo '<li><a href="?' . $key . '=' . $value->getId() . '">' . $value->getName() . '</a></li>';
                }
            }
            ?>
        </ol>
    <?php endif ?>
    <?php if ($data['result']): ?>
        <table id="product-table" class="table table-striped">
            <thead>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                <th>Цена</th>
                <th>Изображение</th>
                <th>Действие</th>
            </tr>
            </thead>

            <tfoot>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                <th>Цена</th>
                <th>Изображение</th>
                <th>Действие</th>
            </tr>
            </tfoot>
            <tbody>
            <?php foreach($data['result'] as $item): ?>
                <tr>
                    <td><?php echo $item->getName(); ?></td>
                    <td><?php echo $item->getDescription(); ?></td>
                    <td><?php echo $item->getPrice() / 100; ?></td>
                    <td><?php echo $item->getImg(); ?></td>
                    <td>&nbsp;</td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <h2>Выберите категорию для редактирования.</h2>
    <?php endif ?>
</section>

<script src="/js/jquery.dataTables.js"></script>
<script src="/js/shCore.js"></script>
<script>
    $('#product-table').dataTable({
        "language": {
            "url": "/resources/ru_RU.lg"
        }
    });
</script>