<style>
    label {
        max-width: 250px;
        float: left;
    }

    input[type="number"], input[type="submit"] {
        max-width: 100px;
    }

    .add {
        width: 22px;
        font-size: 22px;
        cursor: pointer;
        margin: 0;
    }

    .add i {
        vertical-align: middle;
    }
</style>

<!--Блок с информацией о записи в таблице Register-->
<div><p><strong>Данные о записи:</strong></p>
    <table class="table table-striped">
        <tr>
            <th>Дата:</th>
            <th>От кого:</th>
            <th>Кому:</th>
            <th>Тип операции:</th>
            <th>Форма оплаты:</th>
            <th>Статус:</th>
            <th>Кто оформил:</th>
        </tr>
        <tr>
        <?php
        $register = $this->register->getArrayCopy();

        echo '<td>' . $register['date']->format('d.m.Y') .'</td>',
             '<td>' . $register['idStoreFrom']->getName() .'</td>',
             '<td>' . $register['idStoreTo']->getName() .'</td>',
             '<td>' . $register['idOperation']->getName() .'</td>',
             '<td>' . $register['idPaymentType']->getName() .'</td>',
             '<td>' . $register['idStatus']->getName() .'</td>',
             '<td>' . $register['idUser']->getEmail() .'</td>';
        ?>
        </tr>
    </table>
</div>
<!--Конец блока с информацией о записи в таблице Register-->

<!--Блок с информацией о записи товаров в таблице RegisterTable-->
<div><p><strong>Товары:</strong></p>
    <?php if ($this->productList) : ?>

    <table id="productList-table" class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Производитель</th>
            <th>Категория</th>
            <th>Название</th>
            <th>К-во</th>
            <th>Цена</th>
            <th>Сумма</th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->productList as $item): ?>
        <tr>
            <td><?php echo $item['brand']; ?></td>
            <td><?php echo $item['category']; ?></td>
            <td><?php echo $item['name']; ?></td>
            <td><input class="qty-input" type="number" min="1" step="1" value="<?php echo $item['qty']; ?>"></td>
            <td><input class="price-input" type="number" min="0.01" step="0.01" value="<?php echo $item['price']; ?>"></td>
            <td class="sum"><?php echo $item['price'] * $item['qty']; ?></td>
            <td>
                <form class="edit-product">
                    <label class="btn-edit" style="padding: 0">
                        <input class="hidden-edit" name="idProduct" type="hidden" value="<?php echo $item['id']; ?>">
                        <input type="submit" class="btn btn-primary hide">
                        <span class="glyphicon glyphicon-edit" style="cursor: pointer" data-toggle="tooltip" data-placement="top" title="Применить"></span>
                    </label>
                </form>

                <form class="remove-product">
                    <label class="btn-remove" style="padding: 0">
                        <input class="hidden" name="idProduct" type="hidden" value="<?php echo $item['id']; ?>">
                        <input type="submit" class="btn btn-danger hide">
                        <span class="glyphicon glyphicon-remove cross" data-toggle="tooltip" data-placement="top" title="Удалить"></span>
                    </label>
                </form>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<!--Конец блока с информацией о записи товаров в таблице RegisterTable-->
<form method="post" action="add">Нажмите
    <input type="submit" class="btn btn-warning" value="Готово"> если закончили ввод товаров
</form>
<?php endif; ?>

<div>
    <form method="post" action="<?php echo $this->url('register-table');?>" class="float-form" role="form">
        <?php
            echo '<label>Производитель:' . "\n";
            echo '<select class="form-control" name="idBrand">' . "\n";
            echo $this->partialLoop('register/partial/optionLoop.phtml', $this->catalogList['brand']);
            echo '</select>' . "\n";
            echo '</label>' . "\n";

            echo '<label>Категория:' . "\n";
            echo '<select class="form-control" name="idCatalog">' . "\n";
            echo $this->partialLoop('register/partial/optionLoop.phtml', $this->catalogList['category']);
            echo '</select>' . "\n";
            echo '</label>' . "\n";
        ?>
        <input type="submit" class="btn btn-info" name="addFilter" value="Выбрать">
    </form>
</div>
<section>
    <?php if (!is_null($this->product)): ?>

        <?php if (!empty($this->product)) : ?>
        <table id="product-table" class="table table-striped ">
            <thead>
            <tr>
                <th>Название</th>
                <th>К-во / Цена / Действие</th>
            </tr>
            </thead>

            <tfoot>
            <tr>
                <th>Название</th>
                <th>К-во / Цена / Действие</th>
            </tr>
            </tfoot>
            <tbody>
                <?php foreach($this->product as $item): ?>
                    <tr>
                        <td style="max-width: 450px"><?php echo $item->getName(); ?></td>
                        <td>
                            <form method="post" action="<?php echo $this->url('register-table');?>" class="form-inline product-select" role="form">
                                <input type="hidden" name="idProduct" value="<?php echo $item->getId(); ?>">

                                <div class="form-group">
                                    <label class="sr-only" for="qty">К-во:</label>
                                    <input type="number" min="1" step="1" class="form-control qty" name="qty" value="<?php echo $item->getQty(); ?>">
                                </div>

                                <div class="form-group">
                                    <label class="sr-only" for="price">Цена:</label>
                                    <input type="number" min="0" step="0.01" class="form-control price" name="price" value="<?php echo $item->getPrice() / 100; ?>">
                                </div>

                                <div class="form-group">
                                    <label class="add">
                                        <input class="btn btn-default hide add-button" type="submit" value="Добавить">
                                        <i class="glyphicon glyphicon-circle-arrow-up" data-toggle="tooltip" data-placement="top" title="Добавить"></i>
                                    </label>
                                </div>
                            </form>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php else : ?>
            <h2>Таких товаров нет.</h2>
        <?php endif; ?>
    <?php else: ?>
        <h2>Выберите производителя или категорию для продолжения.</h2>
    <?php endif ?>
</section>
<script>
    (function() {
        // Выделить содержимое по клику
        $('.price').on('click', function() {
            $(this).select();
        });

        $('.add-button').on('click', function(e) {
            var qty     = $(this).parent().parent().siblings().find('.qty');
            var price   = $(this).parent().parent().siblings().find('.price');

            if (qty.val() == '') {
                qty.css('border', '1px solid red');

                e.preventDefault();
            }

            if (price.val() < 0) {
                price.css('border', '1px solid red');

                e.preventDefault();
            }
        });

        $(window).on('beforeunload', function() {
            return "Будет создан Нулевой приход!\nПродолжить?";
        });

        $('form').on('submit', function() {
            $(window).off('beforeunload');
        });

        $('a').on('click', function() {
            var answer = confirm("Все не сохраненные данные будут утеряны.\nПродолжить?");

            if (answer) {
                $.ajax({
                    type: 'GET',
                    url: '/register-table/clear'
                });
            }

            return answer;
        });

        // removeSessionProductAction
        $('.remove-product').on('click', function(e) {
            e.preventDefault();

            var val = $(this).find('.hidden').val();

            if (val) {
                $.ajax({
                    type: 'POST',
                    url: '/register-table/remove-session-product',
                    data: { idProduct: val },

                    beforeSend: function() {
                        $('btn-remove').addClass('disabled');
                        $('input[type="submit"]').prop('disabled', true);
                    }
                })
                    .done(function(data) {})
                    .fail(function() {})
                    .always(function() {
                        $('btn-remove').removeClass('disabled');
                        $('input[type="submit"]').prop('disabled', false);
                    });
            }
        });

        $('.btn-remove').on('click', function() {
            $(this).parents('form').parents('tr').fadeOut();
        });

        // editSessionProductAction
        $('.edit-product').on('click', function(e) {
            e.preventDefault();
            var that = $(this);

            var val = that.find('.hidden-edit').val();

            var qty     = that.parents('tr').find('.qty-input').val(),
                price   = that.parents('tr').find('.price-input').val();

            if (val) {
                $.ajax({
                    type: 'POST',
                    url: '/register-table/edit-session-product',
                    data: { idProduct: val, qty:  qty, price: price},

                    beforeSend: function() {
                        $('btn-remove').addClass('disabled');
                        $('input[type="submit"]').prop('disabled', true);
                    }
                })
                    .done(function(data) {})
                    .fail(function() {})
                    .always(function() {
                        $('btn-remove').removeClass('disabled');
                        $('input[type="submit"]').prop('disabled', false);
                    });
            }
        });

        $('.qty-input').add('.price-input').on('change', function() {
            var that = $(this);

            var qty   = parseInt(that.parents('tr').find('.qty-input').val()),
                price = parseFloat(that.parents('tr').find('.price-input').val());

            var sum = (qty * price).toFixed(2);

            that.parents('tr').find('.sum').text(sum);
        });
    })();
</script>