<?php
    $data = $this->product->getVariables();
?>
<link rel="stylesheet" href="/css/jquery.dataTables.css">
<link rel="stylesheet" href="/css/shCore.css">
<style>
    input[type="number"], input[type="submit"] {
        max-width: 80px;
    }

    .add {
        font-size: 18px;
        cursor: pointer;
    }
</style>

<!--Блок с информацией о записи в таблице Register-->
<div>Данные о записи:
    <?php
    $register = $this->register->getArrayCopy();
    $date = new \DateTime($register['date']->getTimestamp);
//    var_dump($date);
//    var_dump($register);
//    echo 'Дата: ' . $date->date;
    echo '<p><strong>От кого:</strong> '      . $register['idStoreFrom']->getName()    . " \n";
    echo '<strong>Кому:</strong> '            . $register['idStoreTo']->getName()      . "</p> \n";
    echo '<p><strong>Тип операции:</strong> ' . $register['idOperation']->getName()    . " \n";
    echo '<strong>Форма оплаты:</strong> '    . $register['idPaymentType']->getName()  . "</p> \n";
    echo '<p><strong>Статус:</strong> '       . $register['idStatus']->getName()       . " \n";
    echo '<strong>Кто оформил:</strong> '     . $register['idUser']->getEmail()        . "</p> \n";
    ?>
</div>
<!--Конец блока с информацией о записи в таблице Register-->

<!--Блок с информацией о записи товаров в таблице RegisterTable-->
<div>Товары:
    <?php if ($this->productList): ;?>
    <table id="productList-table" class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Производитель</th>
            <th>Категория</th>
            <th>Название</th>
            <th>К-во</th>
            <th>Цена</th>
            <th>Сумма</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->productList as $item): ?>
        <tr>
            <td><?php echo $item->brand; ?></td>
            <td><?php echo $item->category; ?></td>
            <td><?php echo $item->getName(); ?></td>
            <td><?php echo $item->currentQty; ?></td>
            <td><?php echo $item->currentPrice; ?></td>
            <td><?php echo $item->currentPrice * $item->currentQty; ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<!--Конец блока с информацией о записи товаров в таблице RegisterTable-->
<form method="post" action="add">Нажмите
    <input type="submit" class="btn btn-warning" value="Готово"> если закончили ввод товаров
</form>
<?php endif; ?>

<section class="col col-lg-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> Каталог товаров</h3>
        <span class="link-type" data-type="<?php echo $this->type;?>"></span>
        <!-- Accordion -->
        <?php echo $this->catalog ;?><!-- /Accordion -->
    </aside>
</section>

<section class="col col-lg-9">
    <?php if (count($data['breadcrumbs']) > 0) : ?>
        <ol class="breadcrumb">
            <?php
            foreach ($data['breadcrumbs'] as $key => $value) {
                if (is_object($value)) {
                    echo '<li><a href="?' . $key . '=' . $value->getId() . '">' . $value->getName() . '</a></li>';
                }
            }
            ?>
        </ol>
    <?php endif ?>

    <?php if ($data['result']): ?>

        <table id="product-table" class="table table-striped">
            <thead>
            <tr>
                <th>Название</th>
                <th>К-во / Цена / Действие</th>
            </tr>
            </thead>

            <tfoot>
            <tr>
                <th>Название</th>
                <th>К-во / Цена / Действие</th>
            </tr>
            </tfoot>
            <tbody>
            <?php foreach($data['result'] as $item): ?>
                <tr>
                    <td style="max-width: 450px"><?php echo $item->getName(); ?></td>
                    <td>
                        <form method="post" action="<?php echo $this->url('register-table');?>" class="form-inline" role="form">
                            <input type="hidden" name="idProduct" value="<?php echo $item->getId(); ?>">

                            <div class="form-group">
                                <label class="sr-only" for="qty">К-во:</label>
                                <input type="number" min="0" step="1" id="qty" class="form-control" name="qty" value="<?php echo $item->qty; ?>">
                            </div>

                            <div class="form-group">
                                <label class="sr-only" for="price">Цена:</label>
                                <input type="number" min="0" step="0.1" id="price" class="form-control" name="price" value="<?php echo $item->getPrice() / 100; ?>">
                            </div>

                            <label style="max-width: 15px" class="add">
                                <input class="btn btn-default hide" type="submit" value="Добавить">
                                <span class="glyphicon glyphicon-circle-arrow-up" data-toggle="tooltip" data-placement="top" title="Добавить"></span>
                            </label>
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <h2>Выберите производителя или категорию для продолжения.</h2>
    <?php endif ?>
</section>

<script src="/js/jquery.dataTables.js"></script>
<script src="/js/shCore.js"></script>
<script>
    $('#product-table').dataTable({
        "language": {
            "url": "/resources/ru_RU.lg"
        }
    });
</script>