<?php
$title = 'Редактирование продукта';
$this->headTitle($title);
?>

<section class="col col-lg-2">
    <p class="back"><span class="glyphicon glyphicon-arrow-left"></span> Назад</p>
</section>
<section class="col col-lg-7">
    <h3><?php echo $this->escapeHtml($title); ?></h3>
    <?php

    $form = $this->form;
    $form->setAttribute('action', $this->url('editproduct',
            array('action' => 'edit',
                  'id'     => $this->id,
            )));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));

    echo '<input type="hidden" name="brand_state" value="'. $this->brandState .'">';
    echo '<input type="hidden" name="catalog_state" value="'. $this->catalogState .'">';

    echo $this->formRow($form->get('name')) . "\n";
    echo $this->formRow($form->get('description')) . "\n";
    echo $this->formRow($form->get('price')) . "\n";

    echo '<label>Список категорий:' . "\n";
    echo '<select class="form-control category_select" name="idCatalog">' . "\n";
    echo $this->partialLoop('product/partial/loops.phtml', $this->catalog);
    echo '</select>' . "\n";
    echo '</label>' . "\n";

    echo '<label>Список производителей:' . "\n";
    echo '<select class="form-control brand_select" name="idBrand">' . "\n";
    echo $this->partialLoop('product/partial/loops.phtml', $this->brand);
    echo '</select>' . "\n";
    echo '</label>' . "\n";

    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</section>