<style>
    .same-width a { width: 144px; }
</style>

<section class="col col-lg-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> Каталог товаров</h3>
        <!-- Accordion -->
        <?php echo $this->catalog ;?><!-- /Accordion -->
    </aside>
</section>

<section class="col col-lg-9 edit-table">
    <?php if (!is_null($this->breadcrumbs)) : ?>
        <div class="filter-criteria">
            <?php foreach ($this->breadcrumbs as $key => $value) : ?>
                <span>
                    <strong><?php echo $value['name']; ?></strong>
                    <a href="/edit-product" data-link="<?php echo $value['translit'];?>">
                        <i class="glyphicon glyphicon-remove cross-link" data-toggle="tooltip" data-placement="top" title="Удалить фильтр"></i>&nbsp;
                    </a>
                </span>
            <?php endforeach; ?>
        </div>
    <?php endif ?>
    <?php if ($this->result): ?>
        <table id="productList-table" class="table table-striped">
        <thead>
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>Цена</th>
            <th>Изображение</th>
            <th><abbr title="Отображение при поиске">Индексирован</abbr></th>
            <th>Действие</th>
        </tr>
        </thead>

        <tfoot>
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>Цена</th>
            <th>Изображение</th>
            <th>Индексирован</th>
            <th>Действие</th>
        </tr>
        </tfoot>
        <tbody>
        <?php for($i = 0, $count = count($this->result); $i < $count; $i++): ?>
            <?php
            if (is_object($this->result[$i]->getIdStatus())) {
                if ($this->result[$i]->getIdStatus()->getId() != 4) {

                    $class = '';
                } else {
                    $class = 'hide_row';
                }
            } else {
                $class = '';
            }
            ?>
            <tr class="<?php echo $class;?>">
                <td><?php echo $this->result[$i]->getName(); ?></td>
                <td><?php echo $this->result[$i]->getDescription() ?: 'Нет'; ?></td>
                <td><?php echo $this->result[$i]->getPrice() / 100; ?></td>
                <td><?php echo $this->result[$i]->getImg() ?
                        '<a href="' . $this->url('editproduct/edit', array('action' => 'img', 'id' => $this->result[$i]->getId())) . '" class="text-img" data-img="/img/product/'. $this->result[$i]->getImg() .'">Да</a>' :
                        '<a href="' . $this->url('editproduct/edit', array('action' => 'img', 'id' => $this->result[$i]->getId())) . '">Нет</a>'; ?>
                </td>
                <td><?php echo $this->result[$i]->getIndexed() ? 'Да' : 'Нет'; ?></td>
                <td class="same-width">
                    <a class="btn btn-primary" href="<?php echo $this->url('editproduct/edit',
                        array('action'=>'edit', 'id' => $this->result[$i]->getId()));?>"><i class="glyphicon glyphicon-edit"></i> Редактировать</a>
                    <a class="btn btn-warning show-hide" href="<?php echo $this->url('editproduct/edit',
                        array('action'=>'hide', 'id' => $this->result[$i]->getId()));?>"><i class="glyphicon glyphicon-eye-close"></i> Скрыть</a>
                </td>
            </tr>
        <?php endfor; ?>
        </tbody>
        </table>
    <?php else: ?>
        <h2>Выберите категорию для редактирования.</h2>
        <h2>Или добавьте <a href="<?php echo $this->url('addproduct', array('action' => 'add'));?>">новый</a> продукт.</h2>
    <?php endif ?>
</section>