<?php
$title = 'Заказы';
$this->headTitle($title);
?>
<section class="col col-lg-12">
    <table id="orderList-table" class="table table-striped">
        <thead>
        <tr>
            <td>Email</td>
            <td>Дата</td>
            <td>Телефон</td>
            <td>Адрес</td>
            <td>Название товара</td>
            <td>К-во товара</td>
            <td>Цена (за ед.)</td>
            <td>Способ доставки</td>
            <td>Способ оплаты</td>
            <td>Комментарий</td>
            <td>Действие</td>
        </tr>
        </thead>

        <tfoot>
        <tr>
            <td>Email</td>
            <td>Дата</td>
            <td>Телефон</td>
            <td>Адрес</td>
            <td>Название товара</td>
            <td>К-во товара</td>
            <td>Цена (за ед.)</td>
            <td>Способ доставки</td>
            <td>Способ оплаты</td>
            <td>Комментарий</td>
            <td>Действие</td>
        </tr>
        </tfoot>

        <tbody>
        <?php foreach ($this->orders as $orderKey => $orderValue) : ?>
            <?php foreach ($orderValue as $orderItem) : ?>
            <tr>
                <td><?php echo $orderKey;?></td>
                <td><?php echo $orderItem['date'];?></td>
                <td><?php echo $orderItem['phone'];?></td>
                <td><?php echo !is_null($orderItem['address'])  ?  $orderItem['address'] : ' - ';?></td>
                <td></td>
                <td></td>
                <td></td>
                <td><?php echo !is_null($orderItem['delivery']) ? $orderItem['delivery'] : ' - ';?></td>
                <td><?php echo !is_null($orderItem['payment'])  ? $orderItem['payment']  : ' - ';?></td>
                <td><?php echo !is_null($orderItem['comment'])  ? $orderItem['comment']  : ' - ';?></td>
                <td></td>
            </tr>
            <?php endforeach; ?>
        <?php endforeach;?>
        </tbody>
    </table>
</section>