<div class="col col-md-7 col-md-offset-2 form_wrap">
    <h3 class="text-center"><?php echo sprintf('Изменить пароль для %s', $this->escapeHtml($this->email)); ?></h3>
    <?php

    $form = $this->resetForm;

    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/resetpassword', array('userId' => $this->userId, 'token' => $this->token)));
    $form->setAttribute('method', 'post');

    echo $this->form()->openTag($form);

    ?>
        <?php echo $this->formLabel($form->get('newCredential')); ?>
        <?php echo $this->formInput($form->get('newCredential')->setAttributes(array(
                'id'          => 'password',
                'class'       => 'form-control form_reset',
                'placeholder' => 'Новый пароль',
                'pattern'     => '^[a-zA-z]{1}[a-zA-Z1-9]{7,20}$',
                'required'    => true
            ))) . $this->formElementErrors($form->get('newCredential')); ?>

        <?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
        <?php echo $this->formInput($form->get('newCredentialVerify')->setAttributes(array(
                'id'          => 'passwordVerify',
                'class'       => 'form-control',
                'placeholder' => 'Еще раз',
                'pattern'     => '^[a-zA-z]{1}[a-zA-Z1-9]{7,20}$',
                'required'    => true
            ))) . $this->formElementErrors($form->get('newCredentialVerify')); ?>

        <?php echo $this->formButton($form->get('submit')->setLabel('Отправить')->setAttribute('class', 'btn btn-primary')); ?>

    <?php echo $this->form()->closeTag(); ?>
</div>
