<h2>Установите ваш пароль для учетной записи</h2>

<p>Аккаунт был создан через адрес электронной почты.</p>
<p>Пожалуйста, нажмите на ссылку ниже, чтобы подтвердить свой адрес электронной почты.</p>

<?php $link = $this->serverUrl() . $this->url('zfcuser/set_password', array('userId' => $user->getId(), 'token' => $registrationRecord->getToken())); ?>
<a href="<?php echo $link ?>">
    <?php echo $link; ?>
</a>