<div class="col col-lg-7 col-lg-offset-2 form_wrap">
    <div id="changem">
    <h3 class="text-center"><?php echo sprintf($this->translate('Change Email for %s'), $this->zfcUserDisplayName()); ?></h3>
    <?php if ($status === true) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Email address changed successfully.'); ?></div>
    <?php elseif ($status === false) : ?>
    <div class="alert alert-danger"><?php echo $this->translate('Unable to update your email address. Please try again.'); ?></div>
    <?php endif; ?>
    <?php

    $form = $this->changeEmailForm;

    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/changeemail'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'change_mail_form');
    $form->setAttribute('name', 'change_mail_form');

    ?>
    <?php echo $this->form()->openTag($form) ?>

        <?php foreach ($form as $element): ?>
        <div class="form-group">
            <?php if ($element->getLabel() != null): ?>
                <?php echo $this->formLabel($element) ?>
            <?php endif ?>
            <?php if ($element instanceof Zend\Form\Element\Button): ?>
                <?php echo $this->formButton($element) ?>
            <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
            <?php else: ?>
                <?php echo $this->formInput($element->setAttributes(array(
                                'class'         => 'form-control',
                                'autocomplete'  => 'off',
                                'required'      => true,
                            )))
                    . $this->formElementErrors($element) ?>
            <?php endif ?>
        </div>

        <?php endforeach ?>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
        <?php endif ?>
        <input id="change_email" class="btn btn-primary" type="submit" value="Отправить" />
    <?php echo $this->form()->closeTag() ?>
    </div>
</div>
