<div class="col col-lg-7 col-lg-offset-2 form_wrap">
    <div id="changep">
    <h3 class="text-center"><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h3>
    <?php if ($status === true) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
    <?php elseif ($status === false) : ?>
    <div class="alert alert-danger"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
    <?php endif; ?>
    <?php

    $form = $this->changePasswordForm;

    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/changepassword'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'change_pass_form');
    $form->setAttribute('name', 'change_pass_form');

    $emailElement = $form->get('identity');
    $emailElement->setValue($this->zfcUserIdentity()->getEmail());

    echo $this->form()->openTag($form);

    ?>

    <?php echo $this->formElementErrors($form->get('identity')); ?>
    <?php echo $this->formInput($form->get('identity')); ?>

    <div class="form-group">
    <?php echo $this->formLabel($form->get('credential')); ?>
    <?php
    echo $this->formInput($form->get('credential')->setAttributes(array(
                    'class'         => 'form-control',
                    'required'      => true))) . $this->formElementErrors($form->get('credential'));
    ?>
    </div>

    <div class="form-group">
    <?php echo $this->formLabel($form->get('newCredential')); ?>
    <?php
    echo $this->formInput($form->get('newCredential')->setAttributes(array(
                    'class'         => 'form-control',
                    'required'      => true))) . $this->formElementErrors($form->get('newCredential'));
    ?>
    </div>

    <div class="form-group">
    <?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
    <?php
    echo $this->formInput($form->get('newCredentialVerify')->setAttributes(array(
                    'class'         => 'form-control',
                    'required'      => true))) . $this->formElementErrors($form->get('newCredentialVerify'));
    ?>
    </div>
        <input id="change_pass" class="btn btn-primary" type="submit" value="Отправить" />
    <?php echo $this->form()->closeTag(); ?>
    </div>
</div>