<div class="col col-lg-7 col-lg-offset-2 form_wrap">
    <h1 class="text-center"><?php echo $this->translate('Sign In'); ?></h1>
    <div>
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'auth_form');
$form->setAttribute('name', 'auth_form');
?>

<?php echo $this->form()->openTag($form) ?>

    <?php echo $this->formElementErrors($form->get('identity')) ?>

    <div class="form-group">
        <label for="identity">Введите Email:</label>
        <input id="identity" name="identity" class="form-control" type="email" value="" placeholder="Введите Email"  pattern="^[\w\.=-]+@[\w\.-]+\.[\w]{2,6}$" required autocomplete="off">
    </div>
    <div class="form-group">
        <label for="credential">Введите Пароль:</label>
        <input id="credential" name="credential" class="form-control" type="password" value="" placeholder="Введите Пароль" pattern="^[a-zA-z]{1}[a-zA-Z1-9]{7,20}$" required>
    </div>

    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>

    <input type="submit" id="auth_btn" class="btn btn btn-primary" name="submit" value="Войти"/>

<?php echo $this->form()->closeTag() ?>
        <?php if ($this->enableRegistration) : ?>
            <p class="sing_in"><?php echo $this->translate('Not registered?'); ?> <a class="register-link" href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a></p>
        <?php endif; ?>
    </div>

</div>
