<div class="col col-lg-7 col-lg-offset-2 form_wrap">
    <div id="reg">
    <h1 class="text-center"><?php echo $this->translate('Register'); ?></h1>

    <?php
    if (!$this->enableRegistration) {
        print "Registration is disabled";
        return;
    }
    $form = $this->registerForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/register'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'register_form');
    $form->setAttribute('name', 'register_form');
    ?>

    <?php echo $this->form()->openTag($form) ?>
        <?php foreach ($form as $element): ?>

        <div class="form-group">
            <?php if (!$element instanceof Zend\Form\Element\Button): ?>
                <?php echo $this->formLabel($element) ?>
            <?php endif ?>
            <?php if ($element instanceof Zend\Form\Element\Button): ?>
                <?php echo $this->formButton($element->setAttribute('class', 'btn btn-primary')) ?>
                <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
                <?php else: ?>
                <?php echo $this->formInput($element->setAttributes(array(
                        'class'         => 'form-control',
                        'autocomplete'  => 'off',
                        'required'      => true,
                    )))
                         . $this->formElementErrors($element) ?>
            <?php endif ?>
        </div>

        <?php endforeach ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
    <?php echo $this->form()->closeTag() ?>
        <p class="register"><?php echo $this->translate('Already a member').'?'; ?> <a class="auth-link" href="<?php echo $this->url('zfcuser/login') . '#log' ?>"><?php echo $this->translate('Sign In'); ?></a></p>
    </div>
</div>
