Action "index", controller "Index", module "Data".
<!--Не забыть-->
<div><a href="/data/attribute">Атрибуты</a></div>
<div><a href="/data/operation">Типы операций</a></div>
<div><a href="/data/payment-type">Типы платежей</a></div>
<div><a href="/data/status">Статусы</a></div>
<div><a href="/data/store">Склады</a></div>
<div><a href="/data/delivery-method">Способ доставки</a></div>
<div><a href="/data/payment-method">Способ оплаты</a></div>
<!--убрать-->