Action "index", controller "Index", module "Data".
<!--Не забыть-->
<div><a href="/data/attribute" id="modal" class="hover-shadow">Атрибуты </a></div>
<div><a href="/data/operation" id="modal" class="hover-shadow">Типы операций </a></div>
<div><a href="/data/paymentType" id="modal" class="hover-shadow">Типы платежей </a></div>
<div><a href="/data/status" id="modal" class="hover-shadow">Статусы </a></div>
<div><a href="/data/store" id="modal" class="hover-shadow">Склады </a></div>
<!--убрать-->