<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'User\Module'                     => __DIR__ . '/Module.php',
  'User\Controller\EditController'  => __DIR__ . '/src/User/Controller/EditController.php',
  'User\Controller\IndexController' => __DIR__ . '/src/User/Controller/IndexController.php',
  'User\Entity\Role'                => __DIR__ . '/src/User/Entity/Role.php',
  'User\Entity\User'                => __DIR__ . '/src/User/Entity/User.php',
  'User\Entity\UserAddition'        => __DIR__ . '/src/User/Entity/UserAddition.php',
);
