<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Application',
        'ZendDeveloperTools',
        'ZFTool',
        'DoctrineModule',
        'DoctrineORMModule',
        'ZfcBase',
        'ZfcAdmin',
        'ZfcUser',
        'ZfcUserDoctrineORM',
        'BjyAuthorize',
        'Catalog',
        'User',
        'Cart',
        'Product',
        'GoSession',
        'Register',
        'Data'
        ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
            ),
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php'),
        'config_cache_enabled'     => true,
        'config_cache_key'         => md5('config'),
        'module_map_cache_enabled' => true,
        'module_map_cache_key'     => md5('module_map'),
        'cache_dir'                => './data/cache',
        )
    );
