<?php echo $this->doctype(); ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Klevo'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/misc/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.min.css')
                        ->prependStylesheet($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/holder.min.js') // НЕ забыть удалить!!!
            ->prependFile($this->basePath() . '/js/script.min.js')
            ->prependFile($this->basePath() . '/js/mosaic.min.js')
            ->prependFile($this->basePath() . '/js/jquery.smooth-scroll.min.js')
            ->prependFile($this->basePath() . '/js/jquery.lazyload.min.js')
            ->prependFile($this->basePath() . 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js')
            ->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js')
            ->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <!-- Header toolbar -->
                <section class="col col-md-12 head-toolbar">
                    <?php if ($this->zfcUserIdentity()): ?>
                        <div class="pull-left personal-cabinet">
                            <a href="<?php echo $this->url('personal-cabinet'); ?>">Личный кабинет</a>
                        </div>
                    <?php endif ?>
                    <div class="pull-right enter">
                        <?php if (!$this->zfcUserIdentity()): ?>
                            <a href="<?php echo $this->url('zfcuser/login') . '#log'; ?>">Войти</a>
                            <a href="<?php echo $this->url('zfcuser/register') . '#reg'; ?>">Зарегистрироваться</a>
                        <?php else: ?>
                            <a href="<?php echo $this->url('zfcuser/logout'); ?>">Выйти</a>
                        <?php endif ?>
                    </div>
                </section><!-- /Header toolbar -->
            </div>
            <div class="content row">
                <div class="col col-md-2">
                    <section id="branding">
                        <a href="/" class="brand"></a>
                    </section>
                </div>
                <div class="col col-md-7">
                    <!-- Carousel -->
                    <div class="carousel slide hidden-sm hidden-xs" data-ride="carousel">
                        <section class="carousel-inner">
                            <div class="active item"><img src="holder.js/750x150" alt=""></div>
                            <div class="item"><img src="holder.js/700x150" alt=""></div>
                            <div class="item"><img src="holder.js/700x150" alt=""></div>
                            <div class="item"><img src="holder.js/700x150" alt=""></div>
                            <div class="item"><img src="holder.js/700x150" alt=""></div>
                        </section>
                    </div><!-- /Carousel -->
                </div>
                <div class="col col-md-3">
                    <address>
                        <h4><a href="<?php echo $this->url('contacts'); ?>">г. Днепропетровск,<br> ул. Белостоцкого, 2а</a></h4>
                        <div class="phone">+38(066)777-61-94 <div class="viber" data-toggle="tooltip" data-placement="top" title="Viber"></div><div class="whatsapp" data-toggle="tooltip" data-placement="top" title="WhatsApp"></div></div>
                        <br>
                        <div class="phone">+38(098)777-61-94</div>
                    </address>
                </div>
            </div>
            <!-- Horizontal menu  -->
            <div class="navbar horizontal-nav" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navigation">
                        <span class="sr-only">Главная навигация</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="main-navigation" class="collapse navbar-collapse">
                    <?php echo $this->navigation('navigation')->menu()->setULClass('nav navbar-nav main-nav'); ?>
                </div>
                <div class="grub-data">
                    <?php if ($this->userRole !== 'guest' && $this->userRole !== 'user'): ?>
                        <!-- Admin button -->
                        <li id="control"><a href="<?php echo $this->url('admin');?>"><i class="glyphicon glyphicon-wrench"></i> <?php echo $this->userRole;?></a></li>
                    <?php endif ?>
                </div>
            </div><!-- /Horizontal menu  -->
            <!-- Search and Cart -->
            <div class="content row">
                <div class="col col-md-9">
                    <form method="get" action="<?php echo $this->url('search');?>" id="main-search" name="main-search" role="search">
                        <div class="form-group">
                            <input type="search" class="form-control search-input" name="q" autocomplete="off" placeholder="Искать...">
                            <label>
                                <input class="btn btn-default hide" type="submit">
                                <span class="search glyphicon glyphicon-search" data-toggle="tooltip" data-placement="top" title="Найти"></span>
                            </label>
                        </div>
                    </form>
                </div>
                <div class="col col-md-3">
                    <a href="<?php echo $this->url('cart');?>" class="cart-info"><i class="fa fa-shopping-cart fa-3x fa-fw"></i> (товаров: <strong class="items-in-cart"><?php echo $this->itemsInCart; ?></strong>)</a>
                </div>
            </div><!-- /Search and Cart -->
            <?php echo $this->content; ?>
            <footer id="footer" class="col col-md-12 text-center">
                <!-- Horizontal menu  -->
                <div class="bottom-nav col col-md-8 col-md-offset-4 hidden-sm hidden-xs">
                    <?php echo $this->navigation('navigation')->menu()->setULClass('nav navbar-nav center-block'); ?>
                </div><!-- /Horizontal menu  -->
                <p class="text-muted">&copy; <?php echo date('Y') ?> by Klevo <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <span class="feedback hidden-sm hidden-xs md-trigger" data-modal="modal-4">Обратная связь</span>
        <!-- Feedback form -->
        <div class="md-modal md-effect-1" id="modal-4">
            <div class="md-content">
                <h3>Обратная связь</h3>
                <div>
                    <form action="<?php echo $this->url('feedback'); ?>" method="post" class="feedback-form" name="feedback-form">
                        <div class="form-group">
                            <label for="email" class="control-label">Ваш email: </label>
                            <input type="email" name="email" class="form-control feedback-form-email" id="email" placeholder="Email" required>
                        </div>
                        <div class="form-group">
                        <label for="subject" class="control-label">Тема: </label>
                            <input type="text" name="subject" class="form-control feedback-form-subject" id="subject" placeholder="Тема" required>
                        </div>
                        <div class="form-group">
                            <label for="text" class="control-label">Суть: </label>
                            <textarea class="form-control feedback-form-text" name="text" id="text" placeholder="Суть" required></textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="md-overlay"></div><!-- /Feedback form -->
        <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button"><span class="glyphicon glyphicon-chevron-up"></span></a>
        <div class="good-idea hidden-md hidden-sm hidden-xs"></div>
    </body>
</html>