<?php echo $this->doctype(); ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Klevo '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . 'http://fonts.googleapis.com/css?family=Noto+Serif&subset=latin,cyrillic')
                        ->prependStylesheet($this->basePath() . 'http://fonts.googleapis.com/css?family=Lemon')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/holder.js') // НЕ забыть удалить!!!
            ->prependFile($this->basePath() . '/js/script.js')
            ->prependFile($this->basePath() . '/js/modal.min.js')
            ->prependFile($this->basePath() . '/js/mosaic.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <div class="container">
            <div class="content row">
                <div class="col col-lg-2">
                    <section id="branding" class="text-center">
                        <a href="/" class="brand wobble-vertical">Klevo</a>
                    </section>
                </div>
                <div class="col col-lg-8">
                    <!-- Carousel -->
                    <div class="carousel slide hidden-sm hidden-xs" data-ride="carousel">
                        <section class="carousel-inner">
                            <div class="active item"><img src="holder.js/750x150" alt=""></div>
                            <div class="item"><img src="holder.js/750x150" alt=""></div>
                            <div class="item"><img src="holder.js/750x150" alt=""></div>
                            <div class="item"><img src="holder.js/750x150" alt=""></div>
                            <div class="item"><img src="holder.js/750x150" alt=""></div>
                        </section>
                    </div><!-- /Carousel -->
                </div>
                <div class="col col-lg-2">
                    <address class="text-justify">
                        <strong>
                            <abbr title="Город">г.</abbr> Днепропетровск<br>
                            улица, номер дома<br>
                        </strong>
                        <abbr title="Телефон">Тел.:</abbr> <span>8(800)8080</span><br>
                        <abbr title="Телефон">Тел.:</abbr> <span>8(800)8080</span><br>
                        Факс: <span>8(800)8080</span>
                    </address>
                </div>
            </div>
            <!-- Horizontal menu  -->
            <div class="navbar horizontal-nav center-block" role="navigation">
                <ul class="nav navbar-nav">
                    <li><a href="#" class="hover-shadow">Галерея <span class="glyphicon glyphicon-picture"></span></a></li>
                    <li><a href="#" class="hover-shadow">Статьи <span class="glyphicon glyphicon-pencil"></span></a></li>
                    <li><a href="#" class="hover-shadow">Форум <span class="glyphicon glyphicon-comment"></span></a></li>
                    <li><a href="#" class="hover-shadow">Оплата и доставка <span class="glyphicon glyphicon-shopping-cart"></a></li>
                    <li><a href="#" class="hover-shadow">Контакты <span class="glyphicon glyphicon-earphone"></a></li>
                    <li><a href="#auth" id="modal" class="hover-shadow">Войти <span class="glyphicon glyphicon-user"></a></li>
                </ul>
            </div><!-- /Horizontal menu  -->

            <!-- Don't forget remove -->
            <h1><a href="/catalog" class="cart-info">Catalog</a></h1>
            <!-- End don't forget -->

            <!-- Search and Cart -->
            <div class="content row">
                <div class="col col-lg-9">
                    <form method="post" action="#" id="main-search" role="search">
                        <div class="form-group">
                            <input type="search" class="form-control search-input" placeholder="Искать...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                  <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </div>
                    </form>
                </div>
                <div class="col col-lg-3">
                    <a href="/cart" class="cart-info"><span class="fa fa-shopping-cart fa-3x fa-fw"></span>Корзина (товаров: 0)</a>
                </div>
            </div><!-- /Search and Cart -->
            <?php echo $this->content; ?>
            <footer class="col col-lg-12">
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <a href="#" class="feedback hidden-sm hidden-xs">Обратная связь</a>
    </body>
</html>
