<section class="col col-lg-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> <span class="product-list">Каталог товаров</span></h3>
        <!-- Accordion -->
        <?php echo $this->catalog ;?><!-- /Accordion -->
    </aside>
</section>

<section class="col col-lg-9">
    <h1 class="text-center">Ошибка! :(</h1>
    <h3>К сожалению, что-то пошло не так. Пожалуйста повторите покупку еще раз. Если ошибка повториться, обратитесь к нам по контактным телефонам.
    Приносим извинения за неудобства.</h3>
</section>