<section class="col col-lg-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> <span class="product-list">Каталог товаров</span></h3>
        <!-- Accordion -->
        <?php echo $this->catalog ;?><!-- /Accordion -->
    </aside>
</section>

<section class="col col-lg-9">
    <h4 class="text-center">Вы хотите заказать:</h4>
    <h3><strong><?php echo $this->name; ?></strong></h3>
    <p>Для подтверждения заказа укажите свой телефон и email <small>(не обязательно)</small>.</p>
    <form action="<?php echo $this->url('cart/default', array('action' => 'order')); ?>" method="post" class="order-form center-block">
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-addon form-addon">+380</div>
                <input name="phone" class="form-control order-phone" type="tel" value="<?php echo $this->userInfo['phone'] ;?>" placeholder="Ваш номер" required>
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-addon form-addon email-addon">@</div>
                <input name="email" class="form-control order-email" type="email" value="<?php echo $this->userInfo['email'] ;?>" placeholder="Ваш email">
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Заказать">
    </form>
</section>