<?php
$result = $this->result;
$total  = array_pop($result);
?>
<section class="col col-lg-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> <span class="product-list">Каталог товаров</span></h3>
        <!-- Accordion -->
        <?php echo $this->catalog ;?><!-- /Accordion -->
    </aside>
</section>

<section class="col col-lg-9">
    <h1 class="text-center success-header">Успех</h1>
    <h3>Выш заказ принят. Наш менеджер свяжется с вами в ближайшее время. Спасибо за покупку!</h3>
        <div class="success div-table">
            <div class="div-row">
                <div class="div-cell div-cell-header"></div>
                <div class="div-cell div-cell-header">Название</div>
                <div class="div-cell div-cell-header">Количество</div>
                <div class="div-cell div-cell-header">Цена (за ед.)</div>
                <div class="div-cell div-cell-header"></div>
            </div>
            <?php foreach ($result as $product) : ?>
                <div class="div-row">
                    <div class="div-cell">
                        <?php if ($product['img']): ?>
                            <img class="img-responsive" src="/img/product/<?php echo $product['img'];?>" width="67" alt="">
                        <?php else : ?>
                            <img class="img-responsive" src="/img/product/noimage.png" width="67" alt="">
                        <?php endif; ?>
                    </div>
                    <div class="div-cell">
                        <?php echo $product['name'];?>
                    </div>
                    <div class="div-cell success-product-qty">
                        <div class="form-control success-product-qty"><?php echo $product['quantity'];?></div>
                    </div>
                    <div class="div-cell product-price success-product-price" data-price="<?php echo $product['price'];?>">
                        <?php echo $product['price']  / 100 ;?>
                    </div>
                </div>
            <?php endforeach; ?>
            <div class="div-row">
                <div class="div-cell"></div>
                <div class="div-cell"></div>
                <div class="div-cell div-cell-footer">Итого</div>
                <div class="div-cell div-cell-footer product-price"> <?php echo $total  / 100 ;?></div>
                <div class="div-cell"></div>
            </div>
        </div>
</section>