<style>
    .article-text { max-height: 140px; max-width: 400px; white-space: nowrap; overflow: hidden; }
</style>
<section class="col col-lg-12">
    <p>
        <a class="btn btn-success" href="<?php echo $this->url('edit-article/default', array('action' => 'add'));?>"><i class="glyphicon glyphicon-plus"></i> Добавить статью</a>
        <a class="btn btn-warning" href="<?php echo $this->url('article-img-upload');?>"><i class="glyphicon glyphicon-plus"></i> Добавить изображение</a>
    </p>
        <table id="articleList-table" class="table table-striped">
            <thead>
            <tr>
                <th>Заголовок</th>
                <th>Текст</th>
                <th>Дата</th>
                <th>Действие</th>
            </tr>
            </thead>

            <tfoot>
            <tr>
                <th>Заголовок</th>
                <th>Текст</th>
                <th>Дата</th>
                <th>Действие</th>
            </tr>
            </tfoot>
            <tbody>
            <?php for($i = 0, $count = count($this->articles); $i < $count; $i++): ?>
                <?php
                if (is_object($this->articles[$i]->getIdStatus())) {
                    if ($this->articles[$i]->getIdStatus()->getId() != 4) {

                        $class = '';
                    } else {
                        $class = 'hide_row';
                    }
                } else {
                    $class = '';
                }
                ?>
                <tr class="<?php echo $class;?>">
                    <td><?php echo $this->articles[$i]->getTitle(); ?></td>
                    <td><?php echo $this->articles[$i]->getText(); ?></td>
                    <td><?php echo $this->articles[$i]->getDate()->format('d.m.Y H:i:s'); ?></td>
                    <td class="same-width">
                        <a class="btn btn-primary" href="<?php echo $this->url('edit-article/default',
                            array('action'=>'edit', 'id' => $this->articles[$i]->getId()));?>"><i class="glyphicon glyphicon-edit"></i> Редактировать</a>
                        <a class="btn btn-warning show-hide" href="<?php echo $this->url('edit-article/default',
                            array('action'=>'hide', 'id' => $this->articles[$i]->getId()));?>"><i class="glyphicon glyphicon-eye-close"></i> Скрыть</a>
                    </td>
                </tr>
            <?php endfor; ?>
            </tbody>
        </table>
</section>