<style>
    label {
        max-width: 250px;
        float: left;
    }

    input[type="number"], input[type="submit"] {
        max-width: 100px;
    }

    .add {
        width: 22px;
        font-size: 22px;
        cursor: pointer;
        margin: 0;
    }

    .add i {
        vertical-align: middle;
    }
</style>

<!--Блок с информацией о записи в таблице Order-->
<div><p><strong>Данные о записи:</strong></p>
    <table class="table table-striped">
        <tr>
            <th>Дата:</th>
            <th>От кого:</th>
            <th>Статус:</th>
            <th>Кто оформил:</th>
        </tr>
        <tr>
            <?php
            $order = $this->order->getArrayCopy();

            echo '<td>' . $order['date']->format('d.m.Y') .'</td>',
                '<td>' . $order['idStore']->getName() .'</td>',
                '<td>' . $order['idStatus']->getName() .'</td>',
                '<td>' . $order['idUser']->getEmail() .'</td>';
            ?>
        </tr>
    </table>
</div>
<!--Конец блока с информацией о записи в таблице Order-->

<!--Блок с информацией о записи товаров в таблице OrderTable-->
<div><p><strong>Товары:</strong></p>
    <?php if ($this->productList) : ?>

    <table id="productList-table" class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Производитель</th>
            <th>Категория</th>
            <th>Название</th>
            <th>К-во</th>
            <th>Цена</th>
            <th>Сумма</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->productList as $item): ?>
            <tr>
                <td><?php echo $item['brand']; ?></td>
                <td><?php echo $item['category']; ?></td>
                <td><?php echo $item['name']; ?></td>
                <td><?php echo $item['qty']; ?></td>
                <td><?php echo $item['price']; ?></td>
                <td><?php echo $item['price'] * $item['qty']; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<!--Конец блока с информацией о записи товаров в таблице OrderTable-->
<form method="post" action="<?php echo $this->url('order-table', array('action' => 'add')); ?>">Нажмите
    <input type="submit" class="btn btn-warning" value="Готово"> если закончили ввод товаров
</form>
<?php endif; ?>

<div>
    <form method="post" action="<?php echo $this->url('order-table');?>" class="float-form" role="form">
        <?php
        echo '<label>Производитель:' . "\n";
        echo '<select class="form-control" name="idBrand">' . "\n";
        echo $this->partialLoop('register/partial/optionLoop.phtml', $this->catalogList['brand']);
        echo '</select>' . "\n";
        echo '</label>' . "\n";

        echo '<label>Категория:' . "\n";
        echo '<select class="form-control" name="idCatalog">' . "\n";
        echo $this->partialLoop('register/partial/optionLoop.phtml', $this->catalogList['category']);
        echo '</select>' . "\n";
        echo '</label>' . "\n";
        ?>
        <input type="submit" class="btn btn-info" name="addFilter" value="Выбрать">
    </form>
</div>

<section class="col col-md-12">
    <?php if (!is_null($this->product)): ?>

        <?php if (!empty($this->product)) : ?>
            <table id="product-table" class="table table-striped ">
                <thead>
                <tr>
                    <th>Название</th>
                    <th>К-во / Цена / Действие</th>
                </tr>
                </thead>

                <tfoot>
                <tr>
                    <th>Название</th>
                    <th>К-во / Цена / Действие</th>
                </tr>
                </tfoot>
                <tbody>
                <?php foreach($this->product as $item): ?>
                    <tr>
                        <td style="max-width: 450px"><?php echo $item->getName(); ?></td>
                        <td>
                            <form method="post" action="<?php echo $this->url('order-table');?>" class="form-inline" role="form">
                                <input type="hidden" name="idProduct" value="<?php echo $item->getId(); ?>">

                                <div class="form-group">
                                    <label class="sr-only" for="qty">К-во:</label>
                                    <input type="number" min="1" step="1" class="form-control qty" name="qty" value="<?php echo $item->getQty(); ?>">
                                </div>

                                <div class="form-group">
                                    <label class="sr-only" for="price">Цена:</label>
                                    <input type="number" min="0" step="0.01" class="form-control price" name="price" value="<?php echo $item->getPrice() / 100; ?>">
                                </div>

                                <div class="form-group">
                                    <label class="add">
                                        <input class="btn btn-default hide add-button" type="submit" value="Добавить">
                                        <i class="glyphicon glyphicon-circle-arrow-up" data-toggle="tooltip" data-placement="top" title="Добавить"></i>
                                    </label>
                                </div>
                            </form>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php else : ?>
            <h2>Таких товаров нет.</h2>
        <?php endif; ?>
    <?php else: ?>
        <h2>Выберите производителя или категорию для продолжения.</h2>
    <?php endif ?>
</section>
<script>
    (function() {
        // Выделить содержимое по клику
        $('.price').on('click', function() {
            $(this).select();
        });

        $('.add-button').on('click', function(e) {
            var qty     = $(this).parent().parent().siblings().find('.qty');
            var price   = $(this).parent().parent().siblings().find('.price');

            if (qty.val() == '') {
                qty.css('border', '1px solid red');

                e.preventDefault();
            }

            if (price.val() < 0) {
                price.css('border', '1px solid red');

                e.preventDefault();
            }
        });

        $(window).on('beforeunload', function() {
            return "Будет создан Нулевой заказ!\nПродолжить?";
        });

        $('form').on('submit', function() {
            $(window).off('beforeunload');
        });

        $('a').on('click', function() {
            var answer = confirm("Все не сохраненные данные будут утеряны.\nПродолжить?");

            if (answer) {
                $.ajax({
                    type: 'GET',
                    url: '/order-table/clear'
                });
            }

            return answer;
        });
    })();
</script>