<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Product\Module'                                   => __DIR__ . '/Module.php',
  'Product\Controller\EditController'                => __DIR__ . '/src/Product/Controller/EditController.php',
  'Product\Controller\IndexController'               => __DIR__ . '/src/Product/Controller/IndexController.php',
  'Product\Controller\ParseController'               => __DIR__ . '/src/Product/Controller/ParseController.php',
  'Product\Controller\UploadController'              => __DIR__ . '/src/Product/Controller/UploadController.php',
  'Product\Entity\Product'                           => __DIR__ . '/src/Product/Entity/Product.php',
  'Product\Entity\ProductCurrentQty'                 => __DIR__ . '/src/Product/Entity/ProductCurrentQty.php',
  'Product\Form\ImgUploadForm'                       => __DIR__ . '/src/Product/Form/ImgUploadForm.php',
  'Product\Form\UploadForm'                          => __DIR__ . '/src/Product/Form/UploadForm.php',
  'Product\Model\Product'                            => __DIR__ . '/src/Product/Model/Product.php',
  'Product\View\Helper\Factory\RequestHelperFactory' => __DIR__ . '/src/Product/View/Helper/Factory/RequestHelperFactory.php',
  'Product\View\Helper\Requesthelper'                => __DIR__ . '/src/Product/View/Helper/Requesthelper.php',
);
