<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Search\Module'                                   => __DIR__ . '/Module.php',
  'Search\Controller\IndexController'               => __DIR__ . '/src/Search/Controller/IndexController.php',
  'Search\View\Helper\Factory\RequestHelperFactory' => __DIR__ . '/src/Search/View/Helper/Factory/RequestHelperFactory.php',
  'Search\View\Helper\Requesthelper'                => __DIR__ . '/src/Search/View/Helper/Requesthelper.php',
);
