<?php
//$this->headMeta()->appendHttpEquiv('Refresh',
//        '15;URL=/file-upload');
?>
<section class="col col-lg-7 col-lg-offset-2">
    <h3>Процесс успешно завершен</h3>
    <p>На страницу <a href="<?php echo $this->url('fileupload'); ?>">Загрузка файла</a></p>
    <p>Добавлено записей: <strong><?php echo $this->insertRow; ?></strong></strong></p>
    <p>Пропущено записей: <strong><?php echo $this->skipRow; ?></strong></p>
    <?php if ($this->errorRow > 0): ?>
    <p>Неверный формат данных: <strong><?php echo $this->errorRow; ?></strong></p>
        <table class="table table-striped">
        <?php foreach ($this->errorData as $errorItem) : ?>
            <tr>
                <td><?php echo $errorItem; ?></td>
            </tr>
        <?php endforeach; ?>
        </table>
    <?php endif; ?>
</section>