<h3>Управление сайтом</h3>
<div>
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab0" data-toggle="tab">Разделы:</a></li>
        <li><a href="#tab1" data-toggle="tab">Отчеты и аналитика</a></li>
        <li><a href="#tab2" data-toggle="tab">Справочник товаров</a></li>
        <li><a href="#tab3" data-toggle="tab">Справочники</a></li>
        <li><a href="#tab4" data-toggle="tab">раздел 4</a></li>
        <li><a href="#tab5" data-toggle="tab">раздел 5</a></li>
        <li><a href="#tab6" data-toggle="tab">раздел 6</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab0"></div>
        <div class="tab-pane" id="tab1">
            <a class="" href="<?php echo $this->url('register');?>">Журнал операций</a>
            <a class="" href="<?php echo $this->url('remains');?>">Остатки товара</a>
            <a class="" href="<?php echo $this->url('balance');?>">Баланс</a>
            <a class="" href="<?php echo $this->url('order');?>">Заказы</a>
            <a class="" href="<?php echo $this->url('payment');?>">Платежи</a>
            <a class="" href="<?php echo $this->url('user');?>">Пользователи</a>
        </div>
        <div class="tab-pane" id="tab2">
            <a class="" href="<?php echo $this->url('fileupload');?>">Загрузить продукт из Excel-документа</a>
            <a class="" href="<?php echo $this->url('editproduct');?>">Работа с продуктом</a>
        </div>
        <div class="tab-pane" id="tab3">
            <a class="" href="<?php echo $this->url('brand');?>">Производители</a>
            <a class="" href="<?php echo $this->url('category');?>">Категории</a>
        </div>
        <div class="tab-pane" id="tab4"></div>
        <div class="tab-pane" id="tab5"></div>
        <div class="tab-pane" id="tab6"></div>
    </div>
</div>





