<h3>Управление сайтом</h3>
<div>
    <ul class="nav nav-pills">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Отчеты и аналитика <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a tabindex="-1" href="<?php echo $this->url('register');?>">Журнал операций</a></li>
                <li><a tabindex="-1" href="<?php echo $this->url('remains');?>">Остатки товара</a></li>
                <li><a tabindex="-1" href="<?php echo $this->url('balance');?>">Баланс</a></li>
                <li><a tabindex="-1" href="<?php echo $this->url('order');?>">Заказы</a></li>
                <li><a tabindex="-1" href="<?php echo $this->url('payment');?>">Платежи</a></li>
                <li><a tabindex="-1" href="<?php echo $this->url('user');?>">Пользователи</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Справочник товаров <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a tabindex="-1" href="<?php echo $this->url('editproduct');?>">Работа с продуктом</a></li>
                <li><a tabindex="-1" href="<?php echo $this->url('fileupload');?>">Загрузить продукт из Excel-документа</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Справочники <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a tabindex="-1" href="<?php echo $this->url('brand');?>">Производители</a></li>
                <li><a tabindex="-1" href="<?php echo $this->url('category');?>">Категории</a></li>
                <li><a tabindex="-1" href="<?php echo $this->url('data/store');?>">Поставщики</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Поиск <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a tabindex="-1" href="<?php echo $this->url('search/create', array('action' => 'create'));?>">Создать/Обновить индексы</a></li>
                <li><a tabindex="-1" href="<?php echo $this->url('search/optimize', array('action' => 'optimize'));?>">Оптимизировать индексы</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Статьи <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a tabindex="-1" href="<?php echo $this->url('edit-article');?>">Создать/Редактировать статью</a></li>
                <li><a tabindex="-1" href="<?php echo $this->url('article-img-upload');?>">Загрузить изображение для статьи</a></li>
            </ul>
        </li>
    </ul>
</div>