<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Data\Module'                              => __DIR__ . '/Module.php',
  'Data\Controller\AttributeController'      => __DIR__ . '/src/Data/Controller/AttributeController.php',
  'Data\Controller\CartUserHelpController'   => __DIR__ . '/src/Data/Controller/CartUserHelpController.php',
  'Data\Controller\DeliveryMethodController' => __DIR__ . '/src/Data/Controller/DeliveryMethodController.php',
  'Data\Controller\IndexController'          => __DIR__ . '/src/Data/Controller/IndexController.php',
  'Data\Controller\OperationController'      => __DIR__ . '/src/Data/Controller/OperationController.php',
  'Data\Controller\PaymentMethodController'  => __DIR__ . '/src/Data/Controller/PaymentMethodController.php',
  'Data\Controller\PaymentTypeController'    => __DIR__ . '/src/Data/Controller/PaymentTypeController.php',
  'Data\Controller\StatusController'         => __DIR__ . '/src/Data/Controller/StatusController.php',
  'Data\Controller\StoreController'          => __DIR__ . '/src/Data/Controller/StoreController.php',
  'Data\Entity\Attribute'                    => __DIR__ . '/src/Data/Entity/Attribute.php',
  'Data\Entity\DeliveryMethod'               => __DIR__ . '/src/Data/Entity/DeliveryMethod.php',
  'Data\Entity\Operation'                    => __DIR__ . '/src/Data/Entity/Operation.php',
  'Data\Entity\PaymentMethod'                => __DIR__ . '/src/Data/Entity/PaymentMethod.php',
  'Data\Entity\PaymentType'                  => __DIR__ . '/src/Data/Entity/PaymentType.php',
  'Data\Entity\Status'                       => __DIR__ . '/src/Data/Entity/Status.php',
  'Data\Entity\Store'                        => __DIR__ . '/src/Data/Entity/Store.php',
  'Data\Model\DeliveryMethod'                => __DIR__ . '/src/Data/Model/DeliveryMethod.php',
  'Data\Model\PaymentMethod'                 => __DIR__ . '/src/Data/Model/PaymentMethod.php',
  'Data\Model\Store'                         => __DIR__ . '/src/Data/Model/Store.php',
);
