<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Data\Module'                           => __DIR__ . '/Module.php',
  'Data\Controller\AttributeController'   => __DIR__ . '/src/Data/Controller/AttributeController.php',
  'Data\Controller\IndexController'       => __DIR__ . '/src/Data/Controller/IndexController.php',
  'Data\Controller\OperationController'   => __DIR__ . '/src/Data/Controller/OperationController.php',
  'Data\Controller\PaymentTypeController' => __DIR__ . '/src/Data/Controller/PaymentTypeController.php',
  'Data\Controller\StatusController'      => __DIR__ . '/src/Data/Controller/StatusController.php',
  'Data\Controller\StoreController'       => __DIR__ . '/src/Data/Controller/StoreController.php',
  'Data\Entity\Attribute'                 => __DIR__ . '/src/Data/Entity/Attribute.php',
  'Data\Entity\Operation'                 => __DIR__ . '/src/Data/Entity/Operation.php',
  'Data\Entity\PaymentType'               => __DIR__ . '/src/Data/Entity/PaymentType.php',
  'Data\Entity\Status'                    => __DIR__ . '/src/Data/Entity/Status.php',
  'Data\Entity\Store'                     => __DIR__ . '/src/Data/Entity/Store.php',
);
