<?php
$title = 'Контакты';
$this->headTitle($title);
?>
<section class="col col-md-12">
    <h1 class="text-center">Ниши контакты</h1>
    <div class="row contacts">
        <section class="col col-md-6">
            <ul class="list-unstyled">
                <li><h2 class="text-center contact-phone"><i class="viber-lg"></i><i class="whatsapp-lg"></i>+38(066)777-61-95</h2></li>
                <li><h2 class="text-center contact-phone"><span class="fa fa-mobile-phone fa-2x mobile-phone"></span> +38(098)777-61-94</h2></li>
            </ul>
        </section>
        <section class="col col-md-6">
            <ul class="list-unstyled">
                <li><h2><a href="https://vk.com/id???" target="_blank"><i class="fa fa-vk"></i> vk.com</a></h2></li>
                <li><h2><a href="https://twitter.com/@Klevo_com_ua" target="_blank"><i class="fa fa-twitter twitter"></i> @Klevo_com_ua</a></h2></li>
            </ul>
        </section>
    </div>
    <div class="row map">
        <section class="col col-md-12">
            <h3 class="text-center">Город Днепропетровск, улица Белостоцкого, 2а</h3>
            <div class="text-center">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1322.2337369825543!2d35.065480100000016!3d48.48592730000003!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40dbe29bd1cdc1d1%3A0x78ca2411fd11cfd1!2z0LLRg9C7LiDQkdGW0LvQvtGB0YLQvtGG0YzQutC-0LPQviwgMiwg0JTQvdGW0L_RgNC-0L_QtdGC0YDQvtCy0YHRjNC6LCDQlNC90ZbQv9GA0L7Qv9C10YLRgNC-0LLRgdGM0LrQsCDQvtCx0LvQsNGB0YLRjA!5e0!3m2!1sru!2sua!4v1422372513553" width="100%" height="400" frameborder="0" style="border:0"></iframe>
            </div>
        </section>
    </div>
</section>