<?php
$title = 'Контакты';
$this->headTitle($title);
?>
<section class="col col-md-12">
    <h1 class="text-center">Ниши контакты</h1>
    <div class="row contacts">
        <section class="col col-md-6">
            <ul class="list-unstyled">
                <li><h2 class="text-center contact-phone"><i class="viber-lg"></i><i class="whatsapp-lg"></i>+38(066)777-61-95</h2></li>
                <li><h2 class="text-center contact-phone"><span class="fa fa-mobile-phone fa-2x mobile-phone"></span> +38(098)777-61-94</h2></li>
            </ul>
        </section>
        <section class="col col-md-6">
            <ul class="list-unstyled">
                <li><h2><a href="https://vk.com/id261645071" target="_blank"><i class="fa fa-vk"></i> vk.com</a></h2></li>
                <li><h2><a href="https://twitter.com/@Klevo_com_ua" target="_blank"><i class="fa fa-twitter twitter"></i> @Klevo_com_ua</a></h2></li>
            </ul>
        </section>
    </div>
    <div class="row map">
        <section class="col col-md-12">
            <h3 class="text-center">Город Днепропетровск, улица Белостоцкого, 2а</h3>
            <div class="text-center">
                <iframe src="https://www.google.com/maps/d/embed?mid=zkK8k6zRRcJc.kpEBWBxl6_wM" width="100%" height="400" frameborder="0" style="border:0"></iframe>
            </div>
        </section>
    </div>
</section>