<section class="col col-lg-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> Каталог товаров</h3>
        <!-- Accordion -->
        <?php echo $this->catalog ;?>
        <!-- /Accordion -->
    </aside>
</section>

<section class="col col-lg-6">
    <div id="carousel" class="carousel slide hidden-sm hidden-xs" data-ride="carousel">

        <ol class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
            <li data-target="#carousel" data-slide-to="2"></li>
            <li data-target="#carousel" data-slide-to="3"></li>
            <li data-target="#carousel" data-slide-to="4"></li>
        </ol>

        <section class="carousel-inner">
            <div class="active item">
                <div class="mosaic-block items">
                    <div class="mosaic-overlay">
                        <div class="details">
                            <h4>Товар 1</h4>
                            <p>Информация о товаре. Информация о товаре. Информация о товаре. Информация о товаре.</p>
                        </div>
                    </div>
                    <img src="holder.js/540x350/sky" alt="">
                </div>
            </div>
            <div class="item">
                <div class="mosaic-block items">
                    <div class="mosaic-overlay">
                        <div class="details">
                            <h4>Товар 2</h4>
                            <p>Информация о товаре. Информация о товаре. Информация о товаре. Информация о товаре.</p>
                        </div>
                    </div>
                    <img src="holder.js/540x350/sky" alt="">
                </div>
            </div>
            <div class="item">
                <div class="mosaic-block items">
                    <div class="mosaic-overlay">
                        <div class="details">
                            <h4>Товар 3</h4>
                            <p>Информация о товаре. Информация о товаре. Информация о товаре. Информация о товаре.</p>
                        </div>
                    </div>
                    <img src="holder.js/540x350/sky" alt="">
                </div>
            </div>
            <div class="item">
                <div class="mosaic-block items">
                    <div class="mosaic-overlay">
                        <div class="details">
                            <h4>Товар 4</h4>
                            <p>Информация о товаре. Информация о товаре. Информация о товаре. Информация о товаре.</p>
                        </div>
                    </div>
                    <img src="holder.js/540x350/sky" alt="">
                </div>
            </div>
            <div class="item">
                <div class="mosaic-block items">
                    <div class="mosaic-overlay">
                        <div class="details">
                            <h4>Товар 5</h4>
                            <p>Информация о товаре. Информация о товаре. Информация о товаре. Информация о товаре.</p>
                        </div>
                    </div>
                    <img src="holder.js/540x350/sky" alt="">
                </div>
            </div>
        </section>

        <a class="left carousel-control" href="#carousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
        <a class="right carousel-control" href="#carousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>
</section>

<section class="col col-lg-3">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam dolorem incidunt minus perspiciatis quia quis ratione. Ab, corporis ea eius enim ex explicabo facilis ipsum libero nesciunt quia quidem voluptatem?
</section>