<?php
$title = 'Главная';
$this->headTitle($title);
?>
<section class="col col-md-3">
    <aside class="filter">
        <h3><span class="glyphicon glyphicon-filter"></span> <span class="product-list">Каталог товаров</span></h3>
        <div class="delim"></div>
        <!-- Accordion -->
        <?php echo $this->catalog ;?><!-- /Accordion -->
    </aside>
</section>

<!-- Flash Messenger -->
<div class="flash-messenger hide">
    <?php if (count($this->flashMessages)) : ?>
        <ul class="list-unstyled flash-messages">
            <?php foreach ($this->flashMessages as $msg) : ?>
                <li><?php echo $msg; ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div><!-- /Flash Messenger -->

<section class="col col-md-6">
    <div id="carousel" class="carousel slide hidden-sm hidden-xs" data-ride="carousel">

        <ol class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
            <li data-target="#carousel" data-slide-to="2"></li>
            <li data-target="#carousel" data-slide-to="3"></li>
            <li data-target="#carousel" data-slide-to="4"></li>
        </ol>

        <section class="carousel-inner">
            <div class="active item">
                <div class="mosaic-block items">
                    <div class="mosaic-overlay">
                        <div class="details">
                            <h4>Товар 1</h4>
                            <p>Информация о товаре. Информация о товаре. Информация о товаре. Информация о товаре.</p>
                        </div>
                    </div>
                    <img src="holder.js/540x350/sky" alt="">
                </div>
            </div>
            <div class="item">
                <div class="mosaic-block items">
                    <div class="mosaic-overlay">
                        <div class="details">
                            <h4>Товар 2</h4>
                            <p>Информация о товаре. Информация о товаре. Информация о товаре. Информация о товаре.</p>
                        </div>
                    </div>
                    <img src="holder.js/540x350/sky" alt="">
                </div>
            </div>
            <div class="item">
                <div class="mosaic-block items">
                    <div class="mosaic-overlay">
                        <div class="details">
                            <h4>Товар 3</h4>
                            <p>Информация о товаре. Информация о товаре. Информация о товаре. Информация о товаре.</p>
                        </div>
                    </div>
                    <img src="holder.js/540x350/sky" alt="">
                </div>
            </div>
            <div class="item">
                <div class="mosaic-block items">
                    <div class="mosaic-overlay">
                        <div class="details">
                            <h4>Товар 4</h4>
                            <p>Информация о товаре. Информация о товаре. Информация о товаре. Информация о товаре.</p>
                        </div>
                    </div>
                    <img src="holder.js/540x350/sky" alt="">
                </div>
            </div>
            <div class="item">
                <div class="mosaic-block items">
                    <div class="mosaic-overlay">
                        <div class="details">
                            <h4>Товар 5</h4>
                            <p>Информация о товаре. Информация о товаре. Информация о товаре. Информация о товаре.</p>
                        </div>
                    </div>
                    <img src="holder.js/540x350/sky" alt="">
                </div>
            </div>
        </section>

        <a class="left carousel-control" href="#carousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
        <a class="right carousel-control" href="#carousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>

    <div class="delim hidden-sm hidden-xs"></div>

    <?php if (!is_null($this->top)) : ?>
    <h3 class="text-center hidden-sm hidden-xs">Популярные</h3>
    <div id="carousel-popular" class="carousel carousel-popular slide hidden-sm hidden-xs" data-ride="carousel">

        <ol class="carousel-indicators carousel-popular-indicators activate-indicators">
            <?php for ($i = 0, $count = count($this->top); $i < $count; $i++) : ?>
                <li data-target="#carousel-popular" data-slide-to="<?php echo $i;?>"></li>
            <?php endfor; ?>
        </ol>

        <section class="carousel-inner activate-carousel">
            <?php foreach ($this->top as $topPart) : ?>
                <div class="item">
                <?php foreach ($topPart as $item) : ?>
                    <div class="col popular-product col-md-3"><a href="/product/<?php echo $item['href']; ?>.html" class="thumbnail" title="<?php echo $item['title']; ?>"><img src="/img/product/min/<?php echo $item['img'] ?: 'noimage.png'; ?>" alt=""></a></div>
                <?php endforeach;?>
                </div>
            <?php endforeach;?>
        </section>

        <a class="left carousel-control carousel-popular-control" href="#carousel-popular" data-slide="prev"><i class="fa fa-chevron-left"></i></a>
        <a class="right carousel-control carousel-popular-control" href="#carousel-popular" data-slide="next"><i class="fa fa-chevron-right"></i></a>
    </div>
    <?php endif;?>
</section>

<section class="col col-md-3">
    <div class="article">
        <h3 class="text-center"><a href="<?php echo $this->url('article'); ?>">Новые статьи</a></h3>
        <div class="delim"></div>
        <?php if (!is_null($this->articles)) : ?>
        <div class="last-articles">
            <section class="last-article-item">
                <?php foreach ($this->articles as $item) : ?>
                    <?php if (is_null($item['idStatus']) || ($item['idStatus']->id == 3)): ?>
                        <section class="last-article-item">
                            <h5><a href="<?php echo $this->url('article/view', array('name' => $item['translit'])); ?>"><?php echo $item['title']; ?></a></h5>
                            <div class="article-text"><?php echo strip_tags($item['text']); ?></div>
                        </section>
                    <?php endif;?>
                <?php endforeach;?>
            </section>
        </div>
        <?php else : ?>
            <h4>Статей пока нет</h4>
        <?php endif; ?>
    </div>
</section>
<script src="/js/clamp.min.js"></script>
<script>$('.article-text').each(function(ag,ah){$clamp(ah,{clamp:3,useNativeClamp:false})});</script>