<?php
$title = 'Оплата и доставка';
$this->headTitle($title);
?>
<section class="col col-md-12">
    <div class="row payment-delivery">
        <section class="col col-md-12">
            <h1 class="text-center">Доставка</h1>
            <div class="row">
                <section class="col col-md-6"><h3><i class="fa fa-arrows fa-2x"></i> Новая почта</h3></section>
                <section class="col col-md-6"><h3><i class="fa fa-truck fa-2x"></i> Самовывоз из магазина</h3></section>
            </div>
            <div class="row">
                <section class="col col-md-6"><h3><i class="fa fa-male fa-2x"></i> Курьером по городу</h3></section>
                <section class="col col-md-6"><h3><i class="fa fa-archive fa-2x"></i> Другой способ</h3></section>
            </div>
            <div class="row">
                <h1 class="text-center">Оплата</h1>
                <div class="row">
                    <section class="col col-md-6"><h3><i class="fa fa-money fa-2x"></i> Наличными при получении</h3></section>
                    <section class="col col-md-6"><h3><i class="fa fa-credit-card fa-2x"></i> Перевод на карту ПриватБанка</h3></section>
                </div>
                <div class="row">
                    <section class="col col-md-6"><h3><i class="fa fa-gift fa-2x"></i> Наложенный платеж</h3></section>
                </div>
            </div>
        </section>
    </div>
</section>